#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: retina-cronjobs-binding-${organization_name}
subjects:
  - kind: ServiceAccount
    name: retina-cronjobs-sa-${organization_name}
    namespace: ${namespace}
roleRef:
  kind: ClusterRole
  name: read-all-resources-${organization_name}
  apiGroup: rbac.authorization.k8s.io
