# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: retina-cronjobs-binding-${suffix}
subjects:
  - kind: ServiceAccount
    name: retina-cronjobs-sa-${suffix}
    namespace: ${namespace}
roleRef:
  kind: ClusterRole
  name: retina-cluster-role
  apiGroup: rbac.authorization.k8s.io
