#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: retina-cronjobs-rolebinding-${suffix}
  namespace: ${namespace}
subjects:
  - kind: ServiceAccount
    name: retina-cronjobs-sa-${suffix}
    namespace: ${namespace}
roleRef:
  kind: Role
  name: retina-role
  apiGroup: rbac.authorization.k8s.io
