# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: v1
kind: ServiceAccount
metadata:
  name: retina-cronjobs-sa-${organization_name}
  namespace: ${namespace}
