# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-defrag
  namespace: ${namespace}
spec:
  schedule: "0 3 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
%{ for node in master_nodes ~}
                          - ${node}
%{ endfor ~}
          containers:
            - name: etcd-defrag
              image: ghcr.io/ahrtr/etcd-defrag:v0.18.0
              args:
                - --endpoints=${etcd_endpoints}
                - --cacert=/ca.pem
                - --cert=/client.pem
                - --key=/client-key.pem
                - --cluster
                - --defrag-rule
                - "dbQuotaUsage > 0.8 || dbSize - dbSizeInUse > 200*1024*1024"
              volumeMounts:
                - mountPath: /ca.pem
                  name: ca-crt
                  readOnly: true
                - mountPath: /client.pem
                  name: client-crt
                  readOnly: true
                - mountPath: /client-key.pem
                  name: client-key
                  readOnly: true
          volumes:
            - name: ca-crt
              hostPath:
                path: ${ca_cert_path}
                type: File
            - name: client-crt
              hostPath:
                path: ${client_cert_path}
                type: File
            - name: client-key
              hostPath:
                path: ${client_key_path}
                type: File
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 0
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            - operator: Exists
              effect: NoExecute
