# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI
authToken: ""

# namespaces, set in helm/terraform call with flags
namespaces: []

# secret
secretName: registry-credentials
