# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

stages:
  - ci
  - static
  - build
  - e2e
  - test mode
  - srsue
  - amarisoft zmq
  - viavi
  - amarisoft sdr
  - android
  - mobility
  - multiue
  - singleue
