# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

spec:
  inputs:
    # Build job configuration for web and api triggered pipelines
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
    build_tags:
      type: array
      default: [saas-linux-medium-amd64]
      description: "Tags to use for the build job."
    os:
      type: string
      default: ubuntu-24.04
      description: "Operating system."
    ocudu_target:
      type: string
      default: ""
      description: "Build target. Keep it empty to use the default target."
    compiler:
      type: string
      default: gcc
      description: "Compiler."
    build_args:
      type: string
      default: ""
      description: "Build arguments for the job. It will be passed to cmake"
    uhd_version:
      type: string
      default: ""
      description: "UHD version. Must be a version included in the specified OS builder image."
    dpdk_version:
      type: string
      default: ""
      description: "DPDK version. Must be a version included in the specified OS builder image."
    test_mode:
      type: string
      default: none
      description: "Run ctest selecting tests with labels matching regular expression. `none` wont run any test at all."
    # E2E job configuration for web and api triggered pipelines
    testbed:
      type: string
      default: none
      description: "Retina Testbed configuration to use. Use `none`` to skip e2e tests."
      options:
        - android_b200
        - android_callbox
        - android_x300
        - rf_b200
        - s72
        - s72_fr2
        - test_mode_ru
        - test_mode_ue
        - viavi
        - zmq_1cu2du
        - zmq_2cucp_1cuup_2du
        - zmq_2gnb
        - zmq_mme
        - zmq_ntn
        - zmq_ric
        - zmq_srsue
        - zmq
        - dynamic
        - none
    markers:
      type: string
      default: ""
      description: "Selected pytest marker (label / tag). Tests with that mark will run."
    file_or_dir:
      type: string
      default: ""
      description: "Test file or folder to select. Use relative path from e2e folder. Do not use quotes. Empty for all tests in the folder."
    keywords:
      type: string
      default: ""
      description: "Select tests by keyword expressions. Do not use quotes. This will run tests which contain names that match the given string expression (case-insensitive), which can include Python operators that use filenames, class names and function names as variables"
    retina_args:
      type: string
      default: ""
      description: "Extra retina args for the e2e suite to run"
    launcher_args:
      type: string
      default: ""
      description: "Extra launcher args"
    e2e_timeout:
      type: string
      default: 3 hours
      description: "Timeout for the job."
---
include:
  # Import OCUDU ci tools
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/workflow.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/static.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/gitlab_settings/.gitlab-ci.yml
    inputs:
      ocudu_path: $[[ inputs.ocudu_path ]]
      ocudu_ref: $[[ inputs.ocudu_ref ]]
  # Custom build and e2e jobs triggered from web and api
  - local: templates/build.yml
    inputs:
      ocudu_path: $[[ inputs.ocudu_path ]]
      ocudu_ref: $[[ inputs.ocudu_ref ]]
      ocudu_build_dir: build_retina
      job: build
      rules:
        - if: $ON_WEB
        - if: $ON_API
      tags: $[[ inputs.build_tags ]]
      os: $[[ inputs.os ]]
      compiler: $[[ inputs.compiler ]]
      ocudu_target: $[[ inputs.ocudu_target ]]
      build_args: $[[ inputs.build_args ]]
      uhd_version: $[[ inputs.uhd_version ]]
      dpdk_version: $[[ inputs.dpdk_version ]]
      test_mode: $[[ inputs.test_mode ]]
      cache:
        - key: $[[ inputs.os ]]-$[[ inputs.compiler ]]
          paths: [ocudu/ccache]
          policy: pull-push
  - local: templates/build.yml
    inputs:
      ocudu_path: $[[ inputs.ocudu_path ]]
      ocudu_ref: $[[ inputs.ocudu_ref ]]
      ocudu_build_dir: build_retina
      job: build trx driver
      rules:
        - if: '"$[[ inputs.testbed ]]" !~ /^(zmq|dynamic)/'
          when: never
        - if: $ON_WEB
        - if: $ON_API
      tags: $[[ inputs.build_tags ]]
      os: $[[ inputs.os ]]
      compiler: gcc
      ocudu_target: trx_ocudu_test
      download_urls_pre_build: >
        --user="${AMARISOFT_PACKAGE_REG_USER}" --password="${AMARISOFT_PACKAGE_REG_PWD}" ${AMARISOFT_PACKAGE_REGISTRY}/${AMARISOFT_VERSION}/amarisoft.${AMARISOFT_VERSION}.tar.gz
      build_args: >
        -DENABLE_TRX_DRIVER=True -DTRX_DRIVER_DIR=${CI_PROJECT_DIR}/amarisoft.${AMARISOFT_VERSION}/trx_uhd-${AMARISOFT_VERSION}/
        -DENABLE_EXPORT=True -DENABLE_UHD=False -DENABLE_ZEROMQ=True -DMARCH=x86-64-v3
      test_mode: none
  - local: templates/e2e.yml
    inputs:
      job: e2e
      stage: e2e
      needs:
        - job: build
        - job: build trx driver
          optional: true
      rules:
        - if: '"$[[ inputs.testbed ]]" == "none"'
          when: never
        - if: $ON_WEB
        - if: $ON_API
      testbed: $[[ inputs.testbed ]]
      markers: $[[ inputs.markers ]]
      file_or_dir: $[[ inputs.file_or_dir ]]
      keywords: $[[ inputs.keywords ]]
      retina_args: $[[ inputs.retina_args ]]
      launcher_args: $[[ inputs.launcher_args ]]
      timeout: $[[ inputs.e2e_timeout ]]
  # CI/CD for each item in the repository
  - local: retina/.gitlab-ci.yml
    inputs:
      ocudu_path: $[[ inputs.ocudu_path ]]
      ocudu_ref: $[[ inputs.ocudu_ref ]]
  - local: e2e/.gitlab-ci.yml
    inputs:
      ocudu_path: $[[ inputs.ocudu_path ]]
      ocudu_ref: $[[ inputs.ocudu_ref ]]
  - local: .gitlab-ci-stages.yml
  - local: docs/.gitlab-ci.yml

variables:
  RETINA_REGISTRY_URI: ${CI_REGISTRY_IMAGE}/retina
  RETINA_PYPI_INDEX: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  AMARISOFT_VERSION: "2026-05-13"
  # SKIP_RETINA_CI: "true" # Define this variable to any value to skip retina ci/cd (here or in project settings)

headers:
  extends: .headers
  needs: []

yaml lint:
  stage: static
  image: python:3.12-alpine
  before_script:
    - pip install "yamllint<2"
  script:
    - yamllint -f colored -c .yamllint .
  rules:
    - if: $ON_MR
      changes:
        paths:
          - "**/*.yml"
          - "**/*.yaml"
  needs: []

tf lint:
  stage: static
  image: registry.gitlab.com/components/opentofu/gitlab-opentofu:3.11.0-opentofu1.10.6-alpine
  rules:
    - if: $ON_MR
      changes:
        paths:
          - "**/*.tf"
  script:
    - tofu fmt -check -recursive .
    - |
      find . -name "versions.tf" -not -path "*/example/*" | while read -r f; do
        module=$(dirname "$f")
        echo "== $module =="
        tofu -chdir="$module" init -backend=false && tofu -chdir="$module" validate
        echo ""
      done
  needs: []
