# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file


Copyright 2021-2026 Software Radio Systems Limited

By using this file, you agree to the terms and conditions set
forth in the LICENSE file which can be found at the top level of
the distribution.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ChannelEmulatorType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ChannelEmulatorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ChannelEmulatorType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _ChannelEmulatorType.ValueType  # 0
    TN: _ChannelEmulatorType.ValueType  # 1
    NTN: _ChannelEmulatorType.ValueType  # 2

class ChannelEmulatorType(_ChannelEmulatorType, metaclass=_ChannelEmulatorTypeEnumTypeWrapper): ...

UNKNOWN: ChannelEmulatorType.ValueType  # 0
TN: ChannelEmulatorType.ValueType  # 1
NTN: ChannelEmulatorType.ValueType  # 2
Global___ChannelEmulatorType: typing_extensions.TypeAlias = ChannelEmulatorType

@typing.final
class RetinaInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGENT_VERSION_FIELD_NUMBER: builtins.int
    SUT_VERSION_FIELD_NUMBER: builtins.int
    agent_version: builtins.str
    sut_version: builtins.str
    def __init__(
        self,
        *,
        agent_version: builtins.str = ...,
        sut_version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["agent_version", b"agent_version", "sut_version", b"sut_version"]) -> None: ...

Global___RetinaInfo: typing_extensions.TypeAlias = RetinaInfo

@typing.final
class Parameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: builtins.str
    value: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "value", b"value"]) -> None: ...

Global___Parameter: typing_extensions.TypeAlias = Parameter

@typing.final
class UEDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIBER_FIELD_NUMBER: builtins.int
    ZMQ_IP_FIELD_NUMBER: builtins.int
    ZMQ_PORT_ARRAY_FIELD_NUMBER: builtins.int
    zmq_ip: builtins.str
    """Empty if not zmq mode"""
    @property
    def subscriber(self) -> Global___Subscriber: ...
    @property
    def zmq_port_array(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        subscriber: Global___Subscriber | None = ...,
        zmq_ip: builtins.str = ...,
        zmq_port_array: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["subscriber", b"subscriber"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["subscriber", b"subscriber", "zmq_ip", b"zmq_ip", "zmq_port_array", b"zmq_port_array"]) -> None: ...

Global___UEDefinition: typing_extensions.TypeAlias = UEDefinition

@typing.final
class Subscriber(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMSI_FIELD_NUMBER: builtins.int
    ALGO_STR_FIELD_NUMBER: builtins.int
    K_FIELD_NUMBER: builtins.int
    OPC_FIELD_NUMBER: builtins.int
    AMF_FIELD_NUMBER: builtins.int
    TEL_FIELD_NUMBER: builtins.int
    SD_FIELD_NUMBER: builtins.int
    imsi: builtins.str
    algo_str: builtins.str
    k: builtins.str
    opc: builtins.str
    amf: builtins.str
    tel: builtins.int
    sd: builtins.str
    def __init__(
        self,
        *,
        imsi: builtins.str = ...,
        algo_str: builtins.str = ...,
        k: builtins.str = ...,
        opc: builtins.str = ...,
        amf: builtins.str = ...,
        tel: builtins.int = ...,
        sd: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["algo_str", b"algo_str", "amf", b"amf", "imsi", b"imsi", "k", b"k", "opc", b"opc", "sd", b"sd", "tel", b"tel"]) -> None: ...

Global___Subscriber: typing_extensions.TypeAlias = Subscriber

@typing.final
class SubscriberArray(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Subscriber]: ...
    def __init__(
        self,
        *,
        value: collections.abc.Iterable[Global___Subscriber] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

Global___SubscriberArray: typing_extensions.TypeAlias = SubscriberArray

@typing.final
class CUDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CU_IP_FIELD_NUMBER: builtins.int
    CU_PORT_FIELD_NUMBER: builtins.int
    cu_ip: builtins.str
    cu_port: builtins.int
    def __init__(
        self,
        *,
        cu_ip: builtins.str = ...,
        cu_port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cu_ip", b"cu_ip", "cu_port", b"cu_port"]) -> None: ...

Global___CUDefinition: typing_extensions.TypeAlias = CUDefinition

@typing.final
class DUDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ZMQ_IP_FIELD_NUMBER: builtins.int
    ZMQ_PORT_ARRAY_FIELD_NUMBER: builtins.int
    zmq_ip: builtins.str
    """Empty if not zmq mode"""
    @property
    def zmq_port_array(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        zmq_ip: builtins.str = ...,
        zmq_port_array: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["zmq_ip", b"zmq_ip", "zmq_port_array", b"zmq_port_array"]) -> None: ...

Global___DUDefinition: typing_extensions.TypeAlias = DUDefinition

@typing.final
class FiveGCDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMF_IP_FIELD_NUMBER: builtins.int
    AMF_PORT_FIELD_NUMBER: builtins.int
    TUN_IP_FIELD_NUMBER: builtins.int
    TUN_MASK_FIELD_NUMBER: builtins.int
    amf_ip: builtins.str
    amf_port: builtins.int
    tun_ip: builtins.str
    tun_mask: builtins.int
    def __init__(
        self,
        *,
        amf_ip: builtins.str = ...,
        amf_port: builtins.int = ...,
        tun_ip: builtins.str = ...,
        tun_mask: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["amf_ip", b"amf_ip", "amf_port", b"amf_port", "tun_ip", b"tun_ip", "tun_mask", b"tun_mask"]) -> None: ...

Global___FiveGCDefinition: typing_extensions.TypeAlias = FiveGCDefinition

@typing.final
class NearRtRicDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    RIC_IP_FIELD_NUMBER: builtins.int
    RIC_PORT_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    """Bool default value is False"""
    ric_ip: builtins.str
    ric_port: builtins.int
    def __init__(
        self,
        *,
        enabled: builtins.bool = ...,
        ric_ip: builtins.str = ...,
        ric_port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enabled", b"enabled", "ric_ip", b"ric_ip", "ric_port", b"ric_port"]) -> None: ...

Global___NearRtRicDefinition: typing_extensions.TypeAlias = NearRtRicDefinition

@typing.final
class ChannelEmulatorDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    ZMQ_IP_FIELD_NUMBER: builtins.int
    DL_ZMQ_PORT_FIELD_NUMBER: builtins.int
    UL_ZMQ_PORT_FIELD_NUMBER: builtins.int
    type: Global___ChannelEmulatorType.ValueType
    zmq_ip: builtins.str
    """Empty if not zmq mode"""
    dl_zmq_port: builtins.int
    ul_zmq_port: builtins.int
    def __init__(
        self,
        *,
        type: Global___ChannelEmulatorType.ValueType = ...,
        zmq_ip: builtins.str = ...,
        dl_zmq_port: builtins.int = ...,
        ul_zmq_port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dl_zmq_port", b"dl_zmq_port", "type", b"type", "ul_zmq_port", b"ul_zmq_port", "zmq_ip", b"zmq_ip"]) -> None: ...

Global___ChannelEmulatorDefinition: typing_extensions.TypeAlias = ChannelEmulatorDefinition

@typing.final
class PLMN(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MCC_FIELD_NUMBER: builtins.int
    MNC_FIELD_NUMBER: builtins.int
    mcc: builtins.str
    mnc: builtins.str
    def __init__(
        self,
        *,
        mcc: builtins.str = ...,
        mnc: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mcc", b"mcc", "mnc", b"mnc"]) -> None: ...

Global___PLMN: typing_extensions.TypeAlias = PLMN

@typing.final
class StartInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DRYRUN_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    PRE_COMMANDS_FIELD_NUMBER: builtins.int
    POST_COMMANDS_FIELD_NUMBER: builtins.int
    dryrun: builtins.bool
    """Bool default value is False"""
    timeout: builtins.int
    """uint default value is 0"""
    @property
    def pre_commands(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def post_commands(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        dryrun: builtins.bool = ...,
        timeout: builtins.int = ...,
        pre_commands: collections.abc.Iterable[builtins.str] | None = ...,
        post_commands: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dryrun", b"dryrun", "post_commands", b"post_commands", "pre_commands", b"pre_commands", "timeout", b"timeout"]) -> None: ...

Global___StartInfo: typing_extensions.TypeAlias = StartInfo

@typing.final
class PingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    address: builtins.str
    count: builtins.int
    interval: builtins.float
    def __init__(
        self,
        *,
        address: builtins.str = ...,
        count: builtins.int = ...,
        interval: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "count", b"count", "interval", b"interval"]) -> None: ...

Global___PingRequest: typing_extensions.TypeAlias = PingRequest

@typing.final
class PingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    SENT_FIELD_NUMBER: builtins.int
    RECEIVED_FIELD_NUMBER: builtins.int
    MIN_FIELD_NUMBER: builtins.int
    AVG_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    MDEV_FIELD_NUMBER: builtins.int
    status: builtins.bool
    sent: builtins.int
    received: builtins.int
    min: builtins.float
    avg: builtins.float
    max: builtins.float
    mdev: builtins.float
    def __init__(
        self,
        *,
        status: builtins.bool = ...,
        sent: builtins.int = ...,
        received: builtins.int = ...,
        min: builtins.float = ...,
        avg: builtins.float = ...,
        max: builtins.float = ...,
        mdev: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["avg", b"avg", "max", b"max", "mdev", b"mdev", "min", b"min", "received", b"received", "sent", b"sent", "status", b"status"]) -> None: ...

Global___PingResponse: typing_extensions.TypeAlias = PingResponse

@typing.final
class IPerfServer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    ip: builtins.str
    port: builtins.int
    def __init__(
        self,
        *,
        ip: builtins.str = ...,
        port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ip", b"ip", "port", b"port"]) -> None: ...

Global___IPerfServer: typing_extensions.TypeAlias = IPerfServer

@typing.final
class StopResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXIT_CODE_FIELD_NUMBER: builtins.int
    ERROR_COUNT_FIELD_NUMBER: builtins.int
    ERROR_MSG_FIELD_NUMBER: builtins.int
    WARNING_COUNT_FIELD_NUMBER: builtins.int
    WARNING_MSG_FIELD_NUMBER: builtins.int
    exit_code: builtins.int
    error_count: builtins.int
    error_msg: builtins.str
    warning_count: builtins.int
    warning_msg: builtins.str
    def __init__(
        self,
        *,
        exit_code: builtins.int = ...,
        error_count: builtins.int = ...,
        error_msg: builtins.str = ...,
        warning_count: builtins.int = ...,
        warning_msg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_count", b"error_count", "error_msg", b"error_msg", "exit_code", b"exit_code", "warning_count", b"warning_count", "warning_msg", b"warning_msg"]) -> None: ...

Global___StopResponse: typing_extensions.TypeAlias = StopResponse

@typing.final
class Metrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DL_BITRATE_FIELD_NUMBER: builtins.int
    UL_BITRATE_FIELD_NUMBER: builtins.int
    NOF_KO_DL_FIELD_NUMBER: builtins.int
    NOF_KO_UL_FIELD_NUMBER: builtins.int
    NOF_REESTABLISHMENTS_REQUEST_FIELD_NUMBER: builtins.int
    NOF_REESTABLISHMENTS_COMPLETE_FIELD_NUMBER: builtins.int
    NOF_HANDOVERS_FIELD_NUMBER: builtins.int
    NOF_PUCCH_F0F1_INVALID_HARQS_FIELD_NUMBER: builtins.int
    NOF_PUCCH_F2F3F4_INVALID_HARQS_FIELD_NUMBER: builtins.int
    NOF_PUCCH_F2F3F4_INVALID_CSIS_FIELD_NUMBER: builtins.int
    NOF_ERROR_INDICATIONS_FIELD_NUMBER: builtins.int
    MAX_LATE_DL_HARQS_FIELD_NUMBER: builtins.int
    MAX_LATE_UL_HARQS_FIELD_NUMBER: builtins.int
    NOF_LATES_FIELD_NUMBER: builtins.int
    NOF_UNDER_FIELD_NUMBER: builtins.int
    NOF_SEQ_ERR_FIELD_NUMBER: builtins.int
    UE_ARRAY_FIELD_NUMBER: builtins.int
    dl_bitrate: builtins.float
    ul_bitrate: builtins.float
    nof_ko_dl: builtins.int
    nof_ko_ul: builtins.int
    nof_reestablishments_request: builtins.int
    nof_reestablishments_complete: builtins.int
    nof_handovers: builtins.int
    nof_pucch_f0f1_invalid_harqs: builtins.int
    nof_pucch_f2f3f4_invalid_harqs: builtins.int
    nof_pucch_f2f3f4_invalid_csis: builtins.int
    nof_error_indications: builtins.int
    max_late_dl_harqs: builtins.int
    max_late_ul_harqs: builtins.int
    nof_lates: builtins.int
    nof_under: builtins.int
    nof_seq_err: builtins.int
    @property
    def ue_array(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___UeMetrics]: ...
    def __init__(
        self,
        *,
        dl_bitrate: builtins.float = ...,
        ul_bitrate: builtins.float = ...,
        nof_ko_dl: builtins.int = ...,
        nof_ko_ul: builtins.int = ...,
        nof_reestablishments_request: builtins.int = ...,
        nof_reestablishments_complete: builtins.int = ...,
        nof_handovers: builtins.int = ...,
        nof_pucch_f0f1_invalid_harqs: builtins.int = ...,
        nof_pucch_f2f3f4_invalid_harqs: builtins.int = ...,
        nof_pucch_f2f3f4_invalid_csis: builtins.int = ...,
        nof_error_indications: builtins.int = ...,
        max_late_dl_harqs: builtins.int = ...,
        max_late_ul_harqs: builtins.int = ...,
        nof_lates: builtins.int = ...,
        nof_under: builtins.int = ...,
        nof_seq_err: builtins.int = ...,
        ue_array: collections.abc.Iterable[Global___UeMetrics] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dl_bitrate", b"dl_bitrate", "max_late_dl_harqs", b"max_late_dl_harqs", "max_late_ul_harqs", b"max_late_ul_harqs", "nof_error_indications", b"nof_error_indications", "nof_handovers", b"nof_handovers", "nof_ko_dl", b"nof_ko_dl", "nof_ko_ul", b"nof_ko_ul", "nof_lates", b"nof_lates", "nof_pucch_f0f1_invalid_harqs", b"nof_pucch_f0f1_invalid_harqs", "nof_pucch_f2f3f4_invalid_csis", b"nof_pucch_f2f3f4_invalid_csis", "nof_pucch_f2f3f4_invalid_harqs", b"nof_pucch_f2f3f4_invalid_harqs", "nof_reestablishments_complete", b"nof_reestablishments_complete", "nof_reestablishments_request", b"nof_reestablishments_request", "nof_seq_err", b"nof_seq_err", "nof_under", b"nof_under", "ue_array", b"ue_array", "ul_bitrate", b"ul_bitrate"]) -> None: ...

Global___Metrics: typing_extensions.TypeAlias = Metrics

@typing.final
class UeMetrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RNTI_FIELD_NUMBER: builtins.int
    DL_AV_5_SAMPLES_FIELD_NUMBER: builtins.int
    DL_AV_15_SAMPLES_FIELD_NUMBER: builtins.int
    DL_AV_30_SAMPLES_FIELD_NUMBER: builtins.int
    UL_AV_5_SAMPLES_FIELD_NUMBER: builtins.int
    UL_AV_15_SAMPLES_FIELD_NUMBER: builtins.int
    UL_AV_30_SAMPLES_FIELD_NUMBER: builtins.int
    rnti: builtins.int
    dl_av_5_samples: builtins.float
    dl_av_15_samples: builtins.float
    dl_av_30_samples: builtins.float
    ul_av_5_samples: builtins.float
    ul_av_15_samples: builtins.float
    ul_av_30_samples: builtins.float
    def __init__(
        self,
        *,
        rnti: builtins.int = ...,
        dl_av_5_samples: builtins.float = ...,
        dl_av_15_samples: builtins.float = ...,
        dl_av_30_samples: builtins.float = ...,
        ul_av_5_samples: builtins.float = ...,
        ul_av_15_samples: builtins.float = ...,
        ul_av_30_samples: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dl_av_15_samples", b"dl_av_15_samples", "dl_av_30_samples", b"dl_av_30_samples", "dl_av_5_samples", b"dl_av_5_samples", "rnti", b"rnti", "ul_av_15_samples", b"ul_av_15_samples", "ul_av_30_samples", b"ul_av_30_samples", "ul_av_5_samples", b"ul_av_5_samples"]) -> None: ...

Global___UeMetrics: typing_extensions.TypeAlias = UeMetrics
