# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
SPDX-License-Identifier: BSD-3-Clause-Open-MPI
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RetinaInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGENT_VERSION_FIELD_NUMBER: builtins.int
    SUT_VERSION_FIELD_NUMBER: builtins.int
    agent_version: builtins.str
    sut_version: builtins.str
    def __init__(
        self,
        *,
        agent_version: builtins.str = ...,
        sut_version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["agent_version", b"agent_version", "sut_version", b"sut_version"]) -> None: ...

Global___RetinaInfo: typing_extensions.TypeAlias = RetinaInfo

@typing.final
class Parameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: builtins.str
    value: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        value: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "value", b"value"]) -> None: ...

Global___Parameter: typing_extensions.TypeAlias = Parameter

@typing.final
class UEDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIBER_FIELD_NUMBER: builtins.int
    ZMQ_IP_FIELD_NUMBER: builtins.int
    ZMQ_PORT_ARRAY_FIELD_NUMBER: builtins.int
    zmq_ip: builtins.str
    """Empty if not zmq mode"""
    @property
    def subscriber(self) -> Global___Subscriber: ...
    @property
    def zmq_port_array(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        subscriber: Global___Subscriber | None = ...,
        zmq_ip: builtins.str = ...,
        zmq_port_array: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["subscriber", b"subscriber"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["subscriber", b"subscriber", "zmq_ip", b"zmq_ip", "zmq_port_array", b"zmq_port_array"]) -> None: ...

Global___UEDefinition: typing_extensions.TypeAlias = UEDefinition

@typing.final
class Subscriber(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMSI_FIELD_NUMBER: builtins.int
    ALGO_STR_FIELD_NUMBER: builtins.int
    K_FIELD_NUMBER: builtins.int
    OPC_FIELD_NUMBER: builtins.int
    AMF_FIELD_NUMBER: builtins.int
    TEL_FIELD_NUMBER: builtins.int
    SD_FIELD_NUMBER: builtins.int
    imsi: builtins.str
    algo_str: builtins.str
    k: builtins.str
    opc: builtins.str
    amf: builtins.str
    tel: builtins.int
    sd: builtins.str
    def __init__(
        self,
        *,
        imsi: builtins.str = ...,
        algo_str: builtins.str = ...,
        k: builtins.str = ...,
        opc: builtins.str = ...,
        amf: builtins.str = ...,
        tel: builtins.int = ...,
        sd: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["algo_str", b"algo_str", "amf", b"amf", "imsi", b"imsi", "k", b"k", "opc", b"opc", "sd", b"sd", "tel", b"tel"]) -> None: ...

Global___Subscriber: typing_extensions.TypeAlias = Subscriber

@typing.final
class SubscriberArray(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Subscriber]: ...
    def __init__(
        self,
        *,
        value: collections.abc.Iterable[Global___Subscriber] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

Global___SubscriberArray: typing_extensions.TypeAlias = SubscriberArray

@typing.final
class CUCPDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CUCP_IP_FIELD_NUMBER: builtins.int
    CUCP_PORT_FIELD_NUMBER: builtins.int
    cucp_ip: builtins.str
    cucp_port: builtins.int
    def __init__(
        self,
        *,
        cucp_ip: builtins.str = ...,
        cucp_port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cucp_ip", b"cucp_ip", "cucp_port", b"cucp_port"]) -> None: ...

Global___CUCPDefinition: typing_extensions.TypeAlias = CUCPDefinition

@typing.final
class CUUPDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CUUP_IP_FIELD_NUMBER: builtins.int
    E1_PORT_FIELD_NUMBER: builtins.int
    cuup_ip: builtins.str
    e1_port: builtins.int
    def __init__(
        self,
        *,
        cuup_ip: builtins.str = ...,
        e1_port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cuup_ip", b"cuup_ip", "e1_port", b"e1_port"]) -> None: ...

Global___CUUPDefinition: typing_extensions.TypeAlias = CUUPDefinition

@typing.final
class DUDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ZMQ_IP_FIELD_NUMBER: builtins.int
    ZMQ_PORT_ARRAY_FIELD_NUMBER: builtins.int
    zmq_ip: builtins.str
    """Empty if not zmq mode"""
    @property
    def zmq_port_array(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        zmq_ip: builtins.str = ...,
        zmq_port_array: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["zmq_ip", b"zmq_ip", "zmq_port_array", b"zmq_port_array"]) -> None: ...

Global___DUDefinition: typing_extensions.TypeAlias = DUDefinition

@typing.final
class GNBDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DU_DEFINITION_FIELD_NUMBER: builtins.int
    CUCP_DEFINITION_FIELD_NUMBER: builtins.int
    @property
    def du_definition(self) -> Global___DUDefinition: ...
    @property
    def cucp_definition(self) -> Global___CUCPDefinition: ...
    def __init__(
        self,
        *,
        du_definition: Global___DUDefinition | None = ...,
        cucp_definition: Global___CUCPDefinition | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cucp_definition", b"cucp_definition", "du_definition", b"du_definition"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cucp_definition", b"cucp_definition", "du_definition", b"du_definition"]) -> None: ...

Global___GNBDefinition: typing_extensions.TypeAlias = GNBDefinition

@typing.final
class FiveGCDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AMF_IP_FIELD_NUMBER: builtins.int
    AMF_PORT_FIELD_NUMBER: builtins.int
    TUN_IP_FIELD_NUMBER: builtins.int
    TUN_MASK_FIELD_NUMBER: builtins.int
    amf_ip: builtins.str
    amf_port: builtins.int
    tun_ip: builtins.str
    tun_mask: builtins.int
    def __init__(
        self,
        *,
        amf_ip: builtins.str = ...,
        amf_port: builtins.int = ...,
        tun_ip: builtins.str = ...,
        tun_mask: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["amf_ip", b"amf_ip", "amf_port", b"amf_port", "tun_ip", b"tun_ip", "tun_mask", b"tun_mask"]) -> None: ...

Global___FiveGCDefinition: typing_extensions.TypeAlias = FiveGCDefinition

@typing.final
class NearRtRicDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    RIC_IP_FIELD_NUMBER: builtins.int
    RIC_PORT_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    """Bool default value is False"""
    ric_ip: builtins.str
    ric_port: builtins.int
    def __init__(
        self,
        *,
        enabled: builtins.bool = ...,
        ric_ip: builtins.str = ...,
        ric_port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["enabled", b"enabled", "ric_ip", b"ric_ip", "ric_port", b"ric_port"]) -> None: ...

Global___NearRtRicDefinition: typing_extensions.TypeAlias = NearRtRicDefinition

@typing.final
class PLMN(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MCC_FIELD_NUMBER: builtins.int
    MNC_FIELD_NUMBER: builtins.int
    mcc: builtins.str
    mnc: builtins.str
    def __init__(
        self,
        *,
        mcc: builtins.str = ...,
        mnc: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["mcc", b"mcc", "mnc", b"mnc"]) -> None: ...

Global___PLMN: typing_extensions.TypeAlias = PLMN

@typing.final
class StartInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DRYRUN_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    PRE_COMMANDS_FIELD_NUMBER: builtins.int
    POST_COMMANDS_FIELD_NUMBER: builtins.int
    dryrun: builtins.bool
    """Bool default value is False"""
    timeout: builtins.int
    """uint default value is 0"""
    @property
    def pre_commands(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def post_commands(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        dryrun: builtins.bool = ...,
        timeout: builtins.int = ...,
        pre_commands: collections.abc.Iterable[builtins.str] | None = ...,
        post_commands: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dryrun", b"dryrun", "post_commands", b"post_commands", "pre_commands", b"pre_commands", "timeout", b"timeout"]) -> None: ...

Global___StartInfo: typing_extensions.TypeAlias = StartInfo

@typing.final
class PingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    address: builtins.str
    count: builtins.int
    interval: builtins.float
    def __init__(
        self,
        *,
        address: builtins.str = ...,
        count: builtins.int = ...,
        interval: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "count", b"count", "interval", b"interval"]) -> None: ...

Global___PingRequest: typing_extensions.TypeAlias = PingRequest

@typing.final
class PingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    SENT_FIELD_NUMBER: builtins.int
    RECEIVED_FIELD_NUMBER: builtins.int
    MIN_FIELD_NUMBER: builtins.int
    AVG_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    MDEV_FIELD_NUMBER: builtins.int
    status: builtins.bool
    sent: builtins.int
    received: builtins.int
    min: builtins.float
    avg: builtins.float
    max: builtins.float
    mdev: builtins.float
    def __init__(
        self,
        *,
        status: builtins.bool = ...,
        sent: builtins.int = ...,
        received: builtins.int = ...,
        min: builtins.float = ...,
        avg: builtins.float = ...,
        max: builtins.float = ...,
        mdev: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["avg", b"avg", "max", b"max", "mdev", b"mdev", "min", b"min", "received", b"received", "sent", b"sent", "status", b"status"]) -> None: ...

Global___PingResponse: typing_extensions.TypeAlias = PingResponse

@typing.final
class IPerfServer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    ip: builtins.str
    port: builtins.int
    def __init__(
        self,
        *,
        ip: builtins.str = ...,
        port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ip", b"ip", "port", b"port"]) -> None: ...

Global___IPerfServer: typing_extensions.TypeAlias = IPerfServer

@typing.final
class StopResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXIT_CODE_FIELD_NUMBER: builtins.int
    ERROR_COUNT_FIELD_NUMBER: builtins.int
    ERROR_MSG_FIELD_NUMBER: builtins.int
    WARNING_COUNT_FIELD_NUMBER: builtins.int
    WARNING_MSG_FIELD_NUMBER: builtins.int
    exit_code: builtins.int
    error_count: builtins.int
    error_msg: builtins.str
    warning_count: builtins.int
    warning_msg: builtins.str
    def __init__(
        self,
        *,
        exit_code: builtins.int = ...,
        error_count: builtins.int = ...,
        error_msg: builtins.str = ...,
        warning_count: builtins.int = ...,
        warning_msg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_count", b"error_count", "error_msg", b"error_msg", "exit_code", b"exit_code", "warning_count", b"warning_count", "warning_msg", b"warning_msg"]) -> None: ...

Global___StopResponse: typing_extensions.TypeAlias = StopResponse

@typing.final
class UeMetrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RNTI_FIELD_NUMBER: builtins.int
    PCI_FIELD_NUMBER: builtins.int
    DL_BITRATE_FIELD_NUMBER: builtins.int
    UL_BITRATE_FIELD_NUMBER: builtins.int
    DL_AV_5_SAMPLES_FIELD_NUMBER: builtins.int
    DL_AV_15_SAMPLES_FIELD_NUMBER: builtins.int
    DL_AV_30_SAMPLES_FIELD_NUMBER: builtins.int
    UL_AV_5_SAMPLES_FIELD_NUMBER: builtins.int
    UL_AV_15_SAMPLES_FIELD_NUMBER: builtins.int
    UL_AV_30_SAMPLES_FIELD_NUMBER: builtins.int
    NOF_KO_DL_FIELD_NUMBER: builtins.int
    NOF_KO_UL_FIELD_NUMBER: builtins.int
    NOF_PUCCH_F0F1_INVALID_HARQS_FIELD_NUMBER: builtins.int
    NOF_PUCCH_F2F3F4_INVALID_HARQS_FIELD_NUMBER: builtins.int
    NOF_PUCCH_F2F3F4_INVALID_CSIS_FIELD_NUMBER: builtins.int
    NOF_PUSCH_INVALID_CSIS_FIELD_NUMBER: builtins.int
    NOF_PUSCH_INVALID_HARQS_FIELD_NUMBER: builtins.int
    NOF_REESTABLISHMENTS_REQUEST_FIELD_NUMBER: builtins.int
    NOF_REESTABLISHMENTS_COMPLETE_FIELD_NUMBER: builtins.int
    NOF_HANDOVERS_FIELD_NUMBER: builtins.int
    NOF_RRC_SUSPEND_FIELD_NUMBER: builtins.int
    NOF_RRC_RESUME_COMPLETE_FIELD_NUMBER: builtins.int
    DL_AVG_RI_FIELD_NUMBER: builtins.int
    UL_AVG_RI_FIELD_NUMBER: builtins.int
    DL_MAX_MCS_FIELD_NUMBER: builtins.int
    UL_MAX_MCS_FIELD_NUMBER: builtins.int
    DL_AV_MID10_SAMPLES_FIELD_NUMBER: builtins.int
    UL_AV_MID10_SAMPLES_FIELD_NUMBER: builtins.int
    BSR_AVG_FIELD_NUMBER: builtins.int
    BSR_MAX_FIELD_NUMBER: builtins.int
    NOF_ETWS_MSG_RECEIVED_FIELD_NUMBER: builtins.int
    NOF_CMAS_MSG_RECEIVED_FIELD_NUMBER: builtins.int
    rnti: builtins.int
    """UE identification"""
    pci: builtins.int
    dl_bitrate: builtins.float
    """Throughput"""
    ul_bitrate: builtins.float
    dl_av_5_samples: builtins.float
    """Peak moving-average bitrates (5 / 15 / 30 samples)"""
    dl_av_15_samples: builtins.float
    dl_av_30_samples: builtins.float
    ul_av_5_samples: builtins.float
    ul_av_15_samples: builtins.float
    ul_av_30_samples: builtins.float
    nof_ko_dl: builtins.int
    """Link quality"""
    nof_ko_ul: builtins.int
    nof_pucch_f0f1_invalid_harqs: builtins.int
    """PUCCH / PUSCH UCI"""
    nof_pucch_f2f3f4_invalid_harqs: builtins.int
    nof_pucch_f2f3f4_invalid_csis: builtins.int
    nof_pusch_invalid_csis: builtins.int
    nof_pusch_invalid_harqs: builtins.int
    nof_reestablishments_request: builtins.int
    """RRC events"""
    nof_reestablishments_complete: builtins.int
    nof_handovers: builtins.int
    nof_rrc_suspend: builtins.int
    nof_rrc_resume_complete: builtins.int
    dl_avg_ri: builtins.float
    """Rank indicator"""
    ul_avg_ri: builtins.float
    dl_max_mcs: builtins.int
    """MCS (maximum observed across the reporting window)"""
    ul_max_mcs: builtins.int
    dl_av_mid10_samples: builtins.float
    """Average of 10 middle samples (all collected samples sorted, extremes trimmed)"""
    ul_av_mid10_samples: builtins.float
    bsr_avg: builtins.float
    """BSR (Buffer Status Report)"""
    bsr_max: builtins.int
    nof_etws_msg_received: builtins.int
    """Async PWS (ETWS secondary / CMAS) receptions, from the UE's own pws_msg event"""
    nof_cmas_msg_received: builtins.int
    def __init__(
        self,
        *,
        rnti: builtins.int = ...,
        pci: builtins.int = ...,
        dl_bitrate: builtins.float = ...,
        ul_bitrate: builtins.float = ...,
        dl_av_5_samples: builtins.float = ...,
        dl_av_15_samples: builtins.float = ...,
        dl_av_30_samples: builtins.float = ...,
        ul_av_5_samples: builtins.float = ...,
        ul_av_15_samples: builtins.float = ...,
        ul_av_30_samples: builtins.float = ...,
        nof_ko_dl: builtins.int = ...,
        nof_ko_ul: builtins.int = ...,
        nof_pucch_f0f1_invalid_harqs: builtins.int = ...,
        nof_pucch_f2f3f4_invalid_harqs: builtins.int = ...,
        nof_pucch_f2f3f4_invalid_csis: builtins.int = ...,
        nof_pusch_invalid_csis: builtins.int = ...,
        nof_pusch_invalid_harqs: builtins.int = ...,
        nof_reestablishments_request: builtins.int = ...,
        nof_reestablishments_complete: builtins.int = ...,
        nof_handovers: builtins.int = ...,
        nof_rrc_suspend: builtins.int = ...,
        nof_rrc_resume_complete: builtins.int = ...,
        dl_avg_ri: builtins.float = ...,
        ul_avg_ri: builtins.float = ...,
        dl_max_mcs: builtins.int = ...,
        ul_max_mcs: builtins.int = ...,
        dl_av_mid10_samples: builtins.float = ...,
        ul_av_mid10_samples: builtins.float = ...,
        bsr_avg: builtins.float = ...,
        bsr_max: builtins.int = ...,
        nof_etws_msg_received: builtins.int = ...,
        nof_cmas_msg_received: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bsr_avg", b"bsr_avg", "bsr_max", b"bsr_max", "dl_av_15_samples", b"dl_av_15_samples", "dl_av_30_samples", b"dl_av_30_samples", "dl_av_5_samples", b"dl_av_5_samples", "dl_av_mid10_samples", b"dl_av_mid10_samples", "dl_avg_ri", b"dl_avg_ri", "dl_bitrate", b"dl_bitrate", "dl_max_mcs", b"dl_max_mcs", "nof_cmas_msg_received", b"nof_cmas_msg_received", "nof_etws_msg_received", b"nof_etws_msg_received", "nof_handovers", b"nof_handovers", "nof_ko_dl", b"nof_ko_dl", "nof_ko_ul", b"nof_ko_ul", "nof_pucch_f0f1_invalid_harqs", b"nof_pucch_f0f1_invalid_harqs", "nof_pucch_f2f3f4_invalid_csis", b"nof_pucch_f2f3f4_invalid_csis", "nof_pucch_f2f3f4_invalid_harqs", b"nof_pucch_f2f3f4_invalid_harqs", "nof_pusch_invalid_csis", b"nof_pusch_invalid_csis", "nof_pusch_invalid_harqs", b"nof_pusch_invalid_harqs", "nof_reestablishments_complete", b"nof_reestablishments_complete", "nof_reestablishments_request", b"nof_reestablishments_request", "nof_rrc_resume_complete", b"nof_rrc_resume_complete", "nof_rrc_suspend", b"nof_rrc_suspend", "pci", b"pci", "rnti", b"rnti", "ul_av_15_samples", b"ul_av_15_samples", "ul_av_30_samples", b"ul_av_30_samples", "ul_av_5_samples", b"ul_av_5_samples", "ul_av_mid10_samples", b"ul_av_mid10_samples", "ul_avg_ri", b"ul_avg_ri", "ul_bitrate", b"ul_bitrate", "ul_max_mcs", b"ul_max_mcs"]) -> None: ...

Global___UeMetrics: typing_extensions.TypeAlias = UeMetrics

@typing.final
class DuMetrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NOF_ERROR_INDICATIONS_FIELD_NUMBER: builtins.int
    MAX_LATE_DL_HARQS_FIELD_NUMBER: builtins.int
    MAX_LATE_UL_HARQS_FIELD_NUMBER: builtins.int
    NOF_LATES_FIELD_NUMBER: builtins.int
    NOF_UNDER_FIELD_NUMBER: builtins.int
    NOF_SEQ_ERR_FIELD_NUMBER: builtins.int
    NOF_SIB1_TRANSMISSIONS_FIELD_NUMBER: builtins.int
    NOF_SIB2_TRANSMISSIONS_FIELD_NUMBER: builtins.int
    NOF_SIB3_TRANSMISSIONS_FIELD_NUMBER: builtins.int
    NOF_SIB4_TRANSMISSIONS_FIELD_NUMBER: builtins.int
    NOF_SIB5_TRANSMISSIONS_FIELD_NUMBER: builtins.int
    NOF_SIB8_TRANSMISSIONS_FIELD_NUMBER: builtins.int
    NOF_PAGING_MESSAGES_FIELD_NUMBER: builtins.int
    NOF_SIB16_TRANSMISSIONS_FIELD_NUMBER: builtins.int
    NOF_SIB19_TRANSMISSIONS_FIELD_NUMBER: builtins.int
    SIB1_HAS_RACH_PRIORITIZATION_SLICE_FIELD_NUMBER: builtins.int
    PRACH_CONFIGURATION_INDEX_FIELD_NUMBER: builtins.int
    TRANSFORM_PRECODER_FIELD_NUMBER: builtins.int
    DRX_LONG_CYCLE_START_OFFSET_FIELD_NUMBER: builtins.int
    T312_FIELD_NUMBER: builtins.int
    C_SRS_FIELD_NUMBER: builtins.int
    B_SRS_FIELD_NUMBER: builtins.int
    PDSCH_PRBS_USED_PER_TDD_SLOT_IDX_FIELD_NUMBER: builtins.int
    PUSCH_PRBS_USED_PER_TDD_SLOT_IDX_FIELD_NUMBER: builtins.int
    PDSCH_PRBS_MID10_PER_TDD_SLOT_IDX_FIELD_NUMBER: builtins.int
    PUSCH_PRBS_MID10_PER_TDD_SLOT_IDX_FIELD_NUMBER: builtins.int
    NOF_RLM_SSB_RESOURCES_FIELD_NUMBER: builtins.int
    NOF_RLM_CSI_RS_RESOURCES_FIELD_NUMBER: builtins.int
    NOF_SIB6_TRANSMISSIONS_FIELD_NUMBER: builtins.int
    NOF_SIB7_TRANSMISSIONS_FIELD_NUMBER: builtins.int
    NOF_CONRES_ISSUES_FIELD_NUMBER: builtins.int
    nof_error_indications: builtins.int
    max_late_dl_harqs: builtins.int
    max_late_ul_harqs: builtins.int
    nof_lates: builtins.int
    nof_under: builtins.int
    nof_seq_err: builtins.int
    nof_sib1_transmissions: builtins.int
    nof_sib2_transmissions: builtins.int
    nof_sib3_transmissions: builtins.int
    nof_sib4_transmissions: builtins.int
    nof_sib5_transmissions: builtins.int
    nof_sib8_transmissions: builtins.int
    nof_paging_messages: builtins.int
    nof_sib16_transmissions: builtins.int
    nof_sib19_transmissions: builtins.int
    sib1_has_rach_prioritization_slice: builtins.bool
    prach_configuration_index: builtins.int
    transform_precoder: builtins.int
    drx_long_cycle_start_offset: builtins.int
    t312: builtins.int
    c_srs: builtins.int
    b_srs: builtins.int
    nof_rlm_ssb_resources: builtins.int
    nof_rlm_csi_rs_resources: builtins.int
    nof_sib6_transmissions: builtins.int
    """ETWS primary notification"""
    nof_sib7_transmissions: builtins.int
    """ETWS secondary notification"""
    nof_conres_issues: builtins.int
    @property
    def pdsch_prbs_used_per_tdd_slot_idx(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def pusch_prbs_used_per_tdd_slot_idx(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def pdsch_prbs_mid10_per_tdd_slot_idx(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def pusch_prbs_mid10_per_tdd_slot_idx(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        nof_error_indications: builtins.int = ...,
        max_late_dl_harqs: builtins.int = ...,
        max_late_ul_harqs: builtins.int = ...,
        nof_lates: builtins.int = ...,
        nof_under: builtins.int = ...,
        nof_seq_err: builtins.int = ...,
        nof_sib1_transmissions: builtins.int = ...,
        nof_sib2_transmissions: builtins.int = ...,
        nof_sib3_transmissions: builtins.int = ...,
        nof_sib4_transmissions: builtins.int = ...,
        nof_sib5_transmissions: builtins.int = ...,
        nof_sib8_transmissions: builtins.int = ...,
        nof_paging_messages: builtins.int = ...,
        nof_sib16_transmissions: builtins.int = ...,
        nof_sib19_transmissions: builtins.int = ...,
        sib1_has_rach_prioritization_slice: builtins.bool = ...,
        prach_configuration_index: builtins.int = ...,
        transform_precoder: builtins.int = ...,
        drx_long_cycle_start_offset: builtins.int = ...,
        t312: builtins.int = ...,
        c_srs: builtins.int = ...,
        b_srs: builtins.int = ...,
        pdsch_prbs_used_per_tdd_slot_idx: collections.abc.Iterable[builtins.int] | None = ...,
        pusch_prbs_used_per_tdd_slot_idx: collections.abc.Iterable[builtins.int] | None = ...,
        pdsch_prbs_mid10_per_tdd_slot_idx: collections.abc.Iterable[builtins.int] | None = ...,
        pusch_prbs_mid10_per_tdd_slot_idx: collections.abc.Iterable[builtins.int] | None = ...,
        nof_rlm_ssb_resources: builtins.int = ...,
        nof_rlm_csi_rs_resources: builtins.int = ...,
        nof_sib6_transmissions: builtins.int = ...,
        nof_sib7_transmissions: builtins.int = ...,
        nof_conres_issues: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["b_srs", b"b_srs", "c_srs", b"c_srs", "drx_long_cycle_start_offset", b"drx_long_cycle_start_offset", "max_late_dl_harqs", b"max_late_dl_harqs", "max_late_ul_harqs", b"max_late_ul_harqs", "nof_conres_issues", b"nof_conres_issues", "nof_error_indications", b"nof_error_indications", "nof_lates", b"nof_lates", "nof_paging_messages", b"nof_paging_messages", "nof_rlm_csi_rs_resources", b"nof_rlm_csi_rs_resources", "nof_rlm_ssb_resources", b"nof_rlm_ssb_resources", "nof_seq_err", b"nof_seq_err", "nof_sib16_transmissions", b"nof_sib16_transmissions", "nof_sib19_transmissions", b"nof_sib19_transmissions", "nof_sib1_transmissions", b"nof_sib1_transmissions", "nof_sib2_transmissions", b"nof_sib2_transmissions", "nof_sib3_transmissions", b"nof_sib3_transmissions", "nof_sib4_transmissions", b"nof_sib4_transmissions", "nof_sib5_transmissions", b"nof_sib5_transmissions", "nof_sib6_transmissions", b"nof_sib6_transmissions", "nof_sib7_transmissions", b"nof_sib7_transmissions", "nof_sib8_transmissions", b"nof_sib8_transmissions", "nof_under", b"nof_under", "pdsch_prbs_mid10_per_tdd_slot_idx", b"pdsch_prbs_mid10_per_tdd_slot_idx", "pdsch_prbs_used_per_tdd_slot_idx", b"pdsch_prbs_used_per_tdd_slot_idx", "prach_configuration_index", b"prach_configuration_index", "pusch_prbs_mid10_per_tdd_slot_idx", b"pusch_prbs_mid10_per_tdd_slot_idx", "pusch_prbs_used_per_tdd_slot_idx", b"pusch_prbs_used_per_tdd_slot_idx", "sib1_has_rach_prioritization_slice", b"sib1_has_rach_prioritization_slice", "t312", b"t312", "transform_precoder", b"transform_precoder"]) -> None: ...

Global___DuMetrics: typing_extensions.TypeAlias = DuMetrics

@typing.final
class CoreMetrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NOF_PDU_SESSION_ESTABLISHMENT_ACCEPT_FIELD_NUMBER: builtins.int
    NOF_NAS_SERVICE_ACCEPT_FIELD_NUMBER: builtins.int
    NOF_NG_PAGING_FIELD_NUMBER: builtins.int
    NOF_TAU_REQUEST_FIELD_NUMBER: builtins.int
    NOF_PDU_SESSION_MODIFICATION_COMPLETE_FIELD_NUMBER: builtins.int
    NOF_PDU_SESSION_MODIFICATION_COMMAND_REJECT_FIELD_NUMBER: builtins.int
    NOF_IMS_NAS_REGISTERED_UE_FIELD_NUMBER: builtins.int
    nof_pdu_session_establishment_accept: builtins.int
    nof_nas_service_accept: builtins.int
    nof_ng_paging: builtins.int
    nof_tau_request: builtins.int
    nof_pdu_session_modification_complete: builtins.int
    nof_pdu_session_modification_command_reject: builtins.int
    nof_ims_nas_registered_ue: builtins.int
    def __init__(
        self,
        *,
        nof_pdu_session_establishment_accept: builtins.int = ...,
        nof_nas_service_accept: builtins.int = ...,
        nof_ng_paging: builtins.int = ...,
        nof_tau_request: builtins.int = ...,
        nof_pdu_session_modification_complete: builtins.int = ...,
        nof_pdu_session_modification_command_reject: builtins.int = ...,
        nof_ims_nas_registered_ue: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nof_ims_nas_registered_ue", b"nof_ims_nas_registered_ue", "nof_nas_service_accept", b"nof_nas_service_accept", "nof_ng_paging", b"nof_ng_paging", "nof_pdu_session_establishment_accept", b"nof_pdu_session_establishment_accept", "nof_pdu_session_modification_command_reject", b"nof_pdu_session_modification_command_reject", "nof_pdu_session_modification_complete", b"nof_pdu_session_modification_complete", "nof_tau_request", b"nof_tau_request"]) -> None: ...

Global___CoreMetrics: typing_extensions.TypeAlias = CoreMetrics

@typing.final
class CuCpMetrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NOF_E_CID_MEASUREMENT_INITIATION_REQUEST_FIELD_NUMBER: builtins.int
    NOF_E_CID_MEASUREMENT_INITIATION_RESPONSE_FIELD_NUMBER: builtins.int
    NOF_E_CID_MEASUREMENT_REPORT_FIELD_NUMBER: builtins.int
    NOF_TRP_INFORMATION_REQUEST_FIELD_NUMBER: builtins.int
    NOF_TRP_INFORMATION_RESPONSE_FIELD_NUMBER: builtins.int
    NOF_XN_HANDOVER_REQUEST_ACKNOWLEDGE_FIELD_NUMBER: builtins.int
    NOF_SN_STATUS_TRANSFER_FIELD_NUMBER: builtins.int
    NOF_ROHC_PROFILE_1_CONFIGURED_FIELD_NUMBER: builtins.int
    NOF_ROHC_PROFILE_2_CONFIGURED_FIELD_NUMBER: builtins.int
    NOF_5QI_1_DRB_CONFIGURED_FIELD_NUMBER: builtins.int
    NOF_5QI_2_DRB_CONFIGURED_FIELD_NUMBER: builtins.int
    NOF_5QI_5_DRB_CONFIGURED_FIELD_NUMBER: builtins.int
    NOF_WRITE_REPLACE_WARNING_REQUEST_FIELD_NUMBER: builtins.int
    NOF_WRITE_REPLACE_WARNING_RESPONSE_FIELD_NUMBER: builtins.int
    nof_e_cid_measurement_initiation_request: builtins.int
    nof_e_cid_measurement_initiation_response: builtins.int
    nof_e_cid_measurement_report: builtins.int
    nof_trp_information_request: builtins.int
    nof_trp_information_response: builtins.int
    nof_xn_handover_request_acknowledge: builtins.int
    nof_sn_status_transfer: builtins.int
    nof_rohc_profile_1_configured: builtins.int
    nof_rohc_profile_2_configured: builtins.int
    nof_5qi_1_drb_configured: builtins.int
    nof_5qi_2_drb_configured: builtins.int
    nof_5qi_5_drb_configured: builtins.int
    nof_write_replace_warning_request: builtins.int
    """NGAP PWS (ETWS/CMAS) trigger from the core"""
    nof_write_replace_warning_response: builtins.int
    def __init__(
        self,
        *,
        nof_e_cid_measurement_initiation_request: builtins.int = ...,
        nof_e_cid_measurement_initiation_response: builtins.int = ...,
        nof_e_cid_measurement_report: builtins.int = ...,
        nof_trp_information_request: builtins.int = ...,
        nof_trp_information_response: builtins.int = ...,
        nof_xn_handover_request_acknowledge: builtins.int = ...,
        nof_sn_status_transfer: builtins.int = ...,
        nof_rohc_profile_1_configured: builtins.int = ...,
        nof_rohc_profile_2_configured: builtins.int = ...,
        nof_5qi_1_drb_configured: builtins.int = ...,
        nof_5qi_2_drb_configured: builtins.int = ...,
        nof_5qi_5_drb_configured: builtins.int = ...,
        nof_write_replace_warning_request: builtins.int = ...,
        nof_write_replace_warning_response: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nof_5qi_1_drb_configured", b"nof_5qi_1_drb_configured", "nof_5qi_2_drb_configured", b"nof_5qi_2_drb_configured", "nof_5qi_5_drb_configured", b"nof_5qi_5_drb_configured", "nof_e_cid_measurement_initiation_request", b"nof_e_cid_measurement_initiation_request", "nof_e_cid_measurement_initiation_response", b"nof_e_cid_measurement_initiation_response", "nof_e_cid_measurement_report", b"nof_e_cid_measurement_report", "nof_rohc_profile_1_configured", b"nof_rohc_profile_1_configured", "nof_rohc_profile_2_configured", b"nof_rohc_profile_2_configured", "nof_sn_status_transfer", b"nof_sn_status_transfer", "nof_trp_information_request", b"nof_trp_information_request", "nof_trp_information_response", b"nof_trp_information_response", "nof_write_replace_warning_request", b"nof_write_replace_warning_request", "nof_write_replace_warning_response", b"nof_write_replace_warning_response", "nof_xn_handover_request_acknowledge", b"nof_xn_handover_request_acknowledge"]) -> None: ...

Global___CuCpMetrics: typing_extensions.TypeAlias = CuCpMetrics

@typing.final
class Metrics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGGREGATE_FIELD_NUMBER: builtins.int
    UE_ARRAY_FIELD_NUMBER: builtins.int
    CU_CP_FIELD_NUMBER: builtins.int
    DU_FIELD_NUMBER: builtins.int
    CORE_FIELD_NUMBER: builtins.int
    @property
    def aggregate(self) -> Global___UeMetrics: ...
    @property
    def ue_array(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___UeMetrics]: ...
    @property
    def cu_cp(self) -> Global___CuCpMetrics: ...
    @property
    def du(self) -> Global___DuMetrics: ...
    @property
    def core(self) -> Global___CoreMetrics: ...
    def __init__(
        self,
        *,
        aggregate: Global___UeMetrics | None = ...,
        ue_array: collections.abc.Iterable[Global___UeMetrics] | None = ...,
        cu_cp: Global___CuCpMetrics | None = ...,
        du: Global___DuMetrics | None = ...,
        core: Global___CoreMetrics | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["aggregate", b"aggregate", "core", b"core", "cu_cp", b"cu_cp", "du", b"du"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["aggregate", b"aggregate", "core", b"core", "cu_cp", b"cu_cp", "du", b"du", "ue_array", b"ue_array"]) -> None: ...

Global___Metrics: typing_extensions.TypeAlias = Metrics
