/*
 *
 * Copyright 2021-2026 Software Radio Systems Limited
 *
 * By using this file, you agree to the terms and conditions set
 * forth in the LICENSE file which can be found at the top level of
 * the distribution.
 *
 */

syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

// Base service provides health checking, version information, and common functionality
service Base {
  // Get agent and binary versions
  rpc GetRetinaInfo(google.protobuf.Empty) returns (RetinaInfo) {};
  // Set parameters at runtime. If fails, it will raise an Error.
  rpc SetParameter(Parameter) returns (google.protobuf.Empty) {};
  // Ping an ip
  rpc Ping(PingRequest) returns (PingResponse) {};
  // Stop the sut in the specified timeout. Returns the exit code
  rpc Stop(google.protobuf.UInt32Value) returns (StopResponse) {};
  // Returns metrics
  rpc GetMetrics(google.protobuf.Empty) returns (Metrics) {};
  // Get Artifacts ID
  rpc GetArtifactsId(google.protobuf.Empty) returns (google.protobuf.StringValue) {};
  // Download the artifacts
  rpc DownloadArtifacts(google.protobuf.Empty) returns (stream google.protobuf.BytesValue) {};
};

message RetinaInfo {
  string agent_version = 1;
  string sut_version   = 2;
};

message Parameter {
  string name  = 1;
  string value = 2;
};

message UEDefinition {
  Subscriber      subscriber     = 1;
  string          zmq_ip         = 2; // Empty if not zmq mode
  repeated uint32 zmq_port_array = 3;
};

message Subscriber {
  string imsi     = 1;
  string algo_str = 2;
  string k        = 3;
  string opc      = 4;
  string amf      = 5;
  uint64 tel      = 6;
  string sd       = 7;
};

message SubscriberArray {
  repeated Subscriber value = 1;
};

message CUDefinition {
  string cu_ip   = 1;
  uint32 cu_port = 2;
};

message DUDefinition {
  string          zmq_ip         = 1; // Empty if not zmq mode
  repeated uint32 zmq_port_array = 2;
};

message FiveGCDefinition {
  string amf_ip   = 1;
  uint32 amf_port = 2;
  string tun_ip   = 3;
  uint32 tun_mask = 4;
};

message NearRtRicDefinition {
  bool   enabled  = 1; // Bool default value is False
  string ric_ip   = 2;
  uint32 ric_port = 3;
};

enum ChannelEmulatorType {
  UNKNOWN = 0;
  TN      = 1;
  NTN     = 2;
}

message ChannelEmulatorDefinition {
  ChannelEmulatorType type        = 1;
  string              zmq_ip      = 2; // Empty if not zmq mode
  uint32              dl_zmq_port = 3;
  uint32              ul_zmq_port = 4;
};

message PLMN {
  string mcc = 1;
  string mnc = 2;
}

message StartInfo {
  bool            dryrun        = 1; // Bool default value is False
  uint32          timeout       = 2; // uint default value is 0
  repeated string pre_commands  = 3;
  repeated string post_commands = 4;
};

message PingRequest {
  string address  = 1;
  uint32 count    = 2;
  double interval = 3;
};

message PingResponse {
  bool   status   = 1;
  uint32 sent     = 2;
  uint32 received = 3;
  double min      = 4;
  double avg      = 5;
  double max      = 6;
  double mdev     = 7;
};

message IPerfServer {
  string ip   = 1;
  uint32 port = 2;
};

message StopResponse {
  int32  exit_code     = 1;
  uint32 error_count   = 2;
  string error_msg     = 3;
  uint32 warning_count = 4;
  string warning_msg   = 5;
};

message Metrics {
  double dl_bitrate = 1;
  double ul_bitrate = 2;
  uint64 nof_ko_dl  = 3;
  uint64 nof_ko_ul  = 4;

  uint32 nof_reestablishments_request  = 5;
  uint32 nof_reestablishments_complete = 6;
  uint32 nof_handovers                 = 7;

  uint32 nof_pucch_f0f1_invalid_harqs   = 8;
  uint32 nof_pucch_f2f3f4_invalid_harqs = 9;
  uint32 nof_pucch_f2f3f4_invalid_csis  = 10;

  uint32 nof_error_indications = 11;
  uint64 max_late_dl_harqs     = 12;
  uint64 max_late_ul_harqs     = 13;

  uint32 nof_lates   = 14;
  uint32 nof_under   = 15;
  uint32 nof_seq_err = 16;

  repeated UeMetrics ue_array = 17;
};

message UeMetrics {
  uint32 rnti             = 1;
  double dl_av_5_samples  = 2;
  double dl_av_15_samples = 3;
  double dl_av_30_samples = 4;
  double ul_av_5_samples  = 5;
  double ul_av_15_samples = 6;
  double ul_av_30_samples = 7;
};