# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
SPDX-License-Identifier: BSD-3-Clause-Open-MPI
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import retina.protocol.base_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ChannelEmulatorStartInfo(google.protobuf.message.Message):
    """Generic Channel Emulator Messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DU_DEFINITION_FIELD_NUMBER: builtins.int
    UE_DEFINITION_FIELD_NUMBER: builtins.int
    START_INFO_FIELD_NUMBER: builtins.int
    @property
    def du_definition(self) -> retina.protocol.base_pb2.DUDefinition:
        """Requird in ZMQ mode"""

    @property
    def ue_definition(self) -> retina.protocol.base_pb2.UEDefinition:
        """Required in ZMQ mode"""

    @property
    def start_info(self) -> retina.protocol.base_pb2.StartInfo: ...
    def __init__(
        self,
        *,
        du_definition: retina.protocol.base_pb2.DUDefinition | None = ...,
        ue_definition: retina.protocol.base_pb2.UEDefinition | None = ...,
        start_info: retina.protocol.base_pb2.StartInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["du_definition", b"du_definition", "start_info", b"start_info", "ue_definition", b"ue_definition"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["du_definition", b"du_definition", "start_info", b"start_info", "ue_definition", b"ue_definition"]) -> None: ...

Global___ChannelEmulatorStartInfo: typing_extensions.TypeAlias = ChannelEmulatorStartInfo
