# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retina/protocol/channel_emulator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'retina/protocol/channel_emulator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from retina.protocol import base_pb2 as retina_dot_protocol_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&retina/protocol/channel_emulator.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1aretina/protocol/base.proto\"\x86\x01\n\x18\x43hannelEmulatorStartInfo\x12$\n\rdu_definition\x18\x01 \x01(\x0b\x32\r.DUDefinition\x12$\n\rue_definition\x18\x02 \x01(\x0b\x32\r.UEDefinition\x12\x1e\n\nstart_info\x18\x03 \x01(\x0b\x32\n.StartInfo2\x96\x01\n\x0f\x43hannelEmulator\x12\x45\n\rGetDefinition\x12\x16.google.protobuf.Empty\x1a\x1a.ChannelEmulatorDefinition\"\x00\x12<\n\x05Start\x12\x19.ChannelEmulatorStartInfo\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retina.protocol.channel_emulator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNELEMULATORSTARTINFO']._serialized_start=100
  _globals['_CHANNELEMULATORSTARTINFO']._serialized_end=234
  _globals['_CHANNELEMULATOR']._serialized_start=237
  _globals['_CHANNELEMULATOR']._serialized_end=387
# @@protoc_insertion_point(module_scope)
