# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from retina.protocol import base_pb2 as retina_dot_protocol_dot_base__pb2
from retina.protocol import channel_emulator_pb2 as retina_dot_protocol_dot_channel__emulator__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in retina/protocol/channel_emulator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChannelEmulatorStub(object):
    """ChannelEmulator service manages wireless channel emulation for testing
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDefinition = channel.unary_unary(
                '/ChannelEmulator/GetDefinition',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_base__pb2.ChannelEmulatorDefinition.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/ChannelEmulator/Start',
                request_serializer=retina_dot_protocol_dot_channel__emulator__pb2.ChannelEmulatorStartInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetScenarioConfigs = channel.unary_unary(
                '/ChannelEmulator/GetScenarioConfigs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_channel__emulator__pb2.ScenarioConfig.FromString,
                _registered_method=True)
        self.GetChannelEmulatorSummary = channel.unary_unary(
                '/ChannelEmulator/GetChannelEmulatorSummary',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_channel__emulator__pb2.ChannelEmulatorSummary.FromString,
                _registered_method=True)


class ChannelEmulatorServicer(object):
    """ChannelEmulator service manages wireless channel emulation for testing
    """

    def GetDefinition(self, request, context):
        """Get Basic information about the Channel Emulator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Start the Channel Emulator. Raise an error if can't be started.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScenarioConfigs(self, request, context):
        """Get scenario configs to be used in gnb and UE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannelEmulatorSummary(self, request, context):
        """Get Channel Emulator Summary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelEmulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefinition,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=retina_dot_protocol_dot_base__pb2.ChannelEmulatorDefinition.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=retina_dot_protocol_dot_channel__emulator__pb2.ChannelEmulatorStartInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetScenarioConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScenarioConfigs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=retina_dot_protocol_dot_channel__emulator__pb2.ScenarioConfig.SerializeToString,
            ),
            'GetChannelEmulatorSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannelEmulatorSummary,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=retina_dot_protocol_dot_channel__emulator__pb2.ChannelEmulatorSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChannelEmulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ChannelEmulator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChannelEmulator(object):
    """ChannelEmulator service manages wireless channel emulation for testing
    """

    @staticmethod
    def GetDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChannelEmulator/GetDefinition',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            retina_dot_protocol_dot_base__pb2.ChannelEmulatorDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChannelEmulator/Start',
            retina_dot_protocol_dot_channel__emulator__pb2.ChannelEmulatorStartInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScenarioConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChannelEmulator/GetScenarioConfigs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            retina_dot_protocol_dot_channel__emulator__pb2.ScenarioConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannelEmulatorSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChannelEmulator/GetChannelEmulatorSummary',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            retina_dot_protocol_dot_channel__emulator__pb2.ChannelEmulatorSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
