# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retina/protocol/fivegc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'retina/protocol/fivegc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from retina.protocol import base_pb2 as retina_dot_protocol_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cretina/protocol/fivegc.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1aretina/protocol/base.proto\"F\n\x0f\x46iveGCStartInfo\x12\x13\n\x04plmn\x18\x01 \x01(\x0b\x32\x05.PLMN\x12\x1e\n\nstart_info\x18\x02 \x01(\x0b\x32\n.StartInfo\"O\n\rIPerfResponse\x12\x1f\n\x08\x64ownlink\x18\x01 \x01(\x0b\x32\r.IPerfSummary\x12\x1d\n\x06uplink\x18\x02 \x01(\x0b\x32\r.IPerfSummary\"\x83\x01\n\x0cIPerfSummary\x12\r\n\x05\x62ytes\x18\x01 \x01(\x04\x12\x17\n\x0f\x62its_per_second\x18\x02 \x01(\x01\x12\x0f\n\x07seconds\x18\x03 \x01(\x01\x12\x14\n\x0clost_packets\x18\x04 \x01(\x04\x12\x0f\n\x07packets\x18\x05 \x01(\x04\x12\x13\n\x0bretransmits\x18\x06 \x01(\x04\x32\xfd\x02\n\x06\x46iveGC\x12<\n\rGetDefinition\x12\x16.google.protobuf.Empty\x1a\x11.FiveGCDefinition\"\x00\x12\x33\n\x05Start\x12\x10.FiveGCStartInfo\x1a\x16.google.protobuf.Empty\"\x00\x12\x38\n\x0f\x41\x64\x64UESubscriber\x12\x0b.Subscriber\x1a\x16.google.protobuf.Empty\"\x00\x12\x41\n\x11StartIPerfService\x12\x1c.google.protobuf.StringValue\x1a\x0c.IPerfServer\"\x00\x12\x32\n\x10StopIPerfService\x12\x0c.IPerfServer\x1a\x0e.IPerfResponse\"\x00\x12O\n!GetImsRegisteredUESubscriberArray\x12\x16.google.protobuf.Empty\x1a\x10.SubscriberArray\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retina.protocol.fivegc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIVEGCSTARTINFO']._serialized_start=121
  _globals['_FIVEGCSTARTINFO']._serialized_end=191
  _globals['_IPERFRESPONSE']._serialized_start=193
  _globals['_IPERFRESPONSE']._serialized_end=272
  _globals['_IPERFSUMMARY']._serialized_start=275
  _globals['_IPERFSUMMARY']._serialized_end=406
  _globals['_FIVEGC']._serialized_start=409
  _globals['_FIVEGC']._serialized_end=790
# @@protoc_insertion_point(module_scope)
