#
# Copyright 2021-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from retina.protocol import base_pb2 as retina_dot_protocol_dot_base__pb2
from retina.protocol import fivegc_pb2 as retina_dot_protocol_dot_fivegc__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in retina/protocol/fivegc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FiveGCStub(object):
    """FiveGC service manages the 5G Core network components
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDefinition = channel.unary_unary(
                '/FiveGC/GetDefinition',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_base__pb2.FiveGCDefinition.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/FiveGC/Start',
                request_serializer=retina_dot_protocol_dot_fivegc__pb2.FiveGCStartInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddUESubscriber = channel.unary_unary(
                '/FiveGC/AddUESubscriber',
                request_serializer=retina_dot_protocol_dot_base__pb2.Subscriber.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StartIPerfService = channel.unary_unary(
                '/FiveGC/StartIPerfService',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_base__pb2.IPerfServer.FromString,
                _registered_method=True)
        self.StopIPerfService = channel.unary_unary(
                '/FiveGC/StopIPerfService',
                request_serializer=retina_dot_protocol_dot_base__pb2.IPerfServer.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_fivegc__pb2.IPerfResponse.FromString,
                _registered_method=True)
        self.GetImsRegisteredUESubscriberArray = channel.unary_unary(
                '/FiveGC/GetImsRegisteredUESubscriberArray',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_base__pb2.SubscriberArray.FromString,
                _registered_method=True)


class FiveGCServicer(object):
    """FiveGC service manages the 5G Core network components
    """

    def GetDefinition(self, request, context):
        """Get Basic information about the UE, like public ip or IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Start the 5GC. Raise an error if can't be started.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUESubscriber(self, request, context):
        """Register an UE into the 5GC. Raises an error if fails
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartIPerfService(self, request, context):
        """Start a IPerf Server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopIPerfService(self, request, context):
        """Stop a IPerf Server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImsRegisteredUESubscriberArray(self, request, context):
        """Return an array of Subscribers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FiveGCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefinition,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=retina_dot_protocol_dot_base__pb2.FiveGCDefinition.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=retina_dot_protocol_dot_fivegc__pb2.FiveGCStartInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddUESubscriber': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUESubscriber,
                    request_deserializer=retina_dot_protocol_dot_base__pb2.Subscriber.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StartIPerfService': grpc.unary_unary_rpc_method_handler(
                    servicer.StartIPerfService,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=retina_dot_protocol_dot_base__pb2.IPerfServer.SerializeToString,
            ),
            'StopIPerfService': grpc.unary_unary_rpc_method_handler(
                    servicer.StopIPerfService,
                    request_deserializer=retina_dot_protocol_dot_base__pb2.IPerfServer.FromString,
                    response_serializer=retina_dot_protocol_dot_fivegc__pb2.IPerfResponse.SerializeToString,
            ),
            'GetImsRegisteredUESubscriberArray': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImsRegisteredUESubscriberArray,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=retina_dot_protocol_dot_base__pb2.SubscriberArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FiveGC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FiveGC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FiveGC(object):
    """FiveGC service manages the 5G Core network components
    """

    @staticmethod
    def GetDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FiveGC/GetDefinition',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            retina_dot_protocol_dot_base__pb2.FiveGCDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FiveGC/Start',
            retina_dot_protocol_dot_fivegc__pb2.FiveGCStartInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddUESubscriber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FiveGC/AddUESubscriber',
            retina_dot_protocol_dot_base__pb2.Subscriber.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartIPerfService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FiveGC/StartIPerfService',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            retina_dot_protocol_dot_base__pb2.IPerfServer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopIPerfService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FiveGC/StopIPerfService',
            retina_dot_protocol_dot_base__pb2.IPerfServer.SerializeToString,
            retina_dot_protocol_dot_fivegc__pb2.IPerfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImsRegisteredUESubscriberArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FiveGC/GetImsRegisteredUESubscriberArray',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            retina_dot_protocol_dot_base__pb2.SubscriberArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
