# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file


Copyright 2021-2026 Software Radio Systems Limited

By using this file, you agree to the terms and conditions set
forth in the LICENSE file which can be found at the top level of
the distribution.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import retina.protocol.base_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FiveGCStartInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLMN_FIELD_NUMBER: builtins.int
    START_INFO_FIELD_NUMBER: builtins.int
    @property
    def plmn(self) -> retina.protocol.base_pb2.PLMN: ...
    @property
    def start_info(self) -> retina.protocol.base_pb2.StartInfo: ...
    def __init__(
        self,
        *,
        plmn: retina.protocol.base_pb2.PLMN | None = ...,
        start_info: retina.protocol.base_pb2.StartInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["plmn", b"plmn", "start_info", b"start_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["plmn", b"plmn", "start_info", b"start_info"]) -> None: ...

Global___FiveGCStartInfo: typing_extensions.TypeAlias = FiveGCStartInfo

@typing.final
class IPerfResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOWNLINK_FIELD_NUMBER: builtins.int
    UPLINK_FIELD_NUMBER: builtins.int
    @property
    def downlink(self) -> Global___IPerfSummary: ...
    @property
    def uplink(self) -> Global___IPerfSummary: ...
    def __init__(
        self,
        *,
        downlink: Global___IPerfSummary | None = ...,
        uplink: Global___IPerfSummary | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["downlink", b"downlink", "uplink", b"uplink"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["downlink", b"downlink", "uplink", b"uplink"]) -> None: ...

Global___IPerfResponse: typing_extensions.TypeAlias = IPerfResponse

@typing.final
class IPerfSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BYTES_FIELD_NUMBER: builtins.int
    BITS_PER_SECOND_FIELD_NUMBER: builtins.int
    SECONDS_FIELD_NUMBER: builtins.int
    LOST_PACKETS_FIELD_NUMBER: builtins.int
    PACKETS_FIELD_NUMBER: builtins.int
    RETRANSMITS_FIELD_NUMBER: builtins.int
    bytes: builtins.int
    bits_per_second: builtins.float
    seconds: builtins.float
    lost_packets: builtins.int
    packets: builtins.int
    retransmits: builtins.int
    def __init__(
        self,
        *,
        bytes: builtins.int = ...,
        bits_per_second: builtins.float = ...,
        seconds: builtins.float = ...,
        lost_packets: builtins.int = ...,
        packets: builtins.int = ...,
        retransmits: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bits_per_second", b"bits_per_second", "bytes", b"bytes", "lost_packets", b"lost_packets", "packets", b"packets", "retransmits", b"retransmits", "seconds", b"seconds"]) -> None: ...

Global___IPerfSummary: typing_extensions.TypeAlias = IPerfSummary
