#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retina/protocol/gnb.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'retina/protocol/gnb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from retina.protocol import base_pb2 as retina_dot_protocol_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19retina/protocol/gnb.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1aretina/protocol/base.proto\"p\n\x0b\x43UStartInfo\x12\x13\n\x04plmn\x18\x01 \x01(\x0b\x32\x05.PLMN\x12,\n\x11\x66ivegc_definition\x18\x02 \x01(\x0b\x32\x11.FiveGCDefinition\x12\x1e\n\nstart_info\x18\x03 \x01(\x0b\x32\n.StartInfo\"\xf7\x01\n\x0b\x44UStartInfo\x12\x11\n\tgnb_du_id\x18\x01 \x01(\x04\x12\x13\n\x04plmn\x18\x02 \x01(\x0b\x32\x05.PLMN\x12\x11\n\tnum_cells\x18\x03 \x01(\r\x12\x13\n\x0b\x63\x65ll_offset\x18\x04 \x01(\r\x12$\n\rcu_definition\x18\x05 \x01(\x0b\x32\r.CUDefinition\x12$\n\rue_definition\x18\x06 \x01(\x0b\x32\r.UEDefinition\x12,\n\x0eric_definition\x18\x07 \x01(\x0b\x32\x14.NearRtRicDefinition\x12\x1e\n\nstart_info\x18\x08 \x01(\x0b\x32\n.StartInfo\"\xc5\x01\n\x0cGNBStartInfo\x12\x13\n\x04plmn\x18\x01 \x01(\x0b\x32\x05.PLMN\x12,\n\x11\x66ivegc_definition\x18\x02 \x01(\x0b\x32\x11.FiveGCDefinition\x12$\n\rue_definition\x18\x03 \x01(\x0b\x32\r.UEDefinition\x12,\n\x0eric_definition\x18\x04 \x01(\x0b\x32\x14.NearRtRicDefinition\x12\x1e\n\nstart_info\x18\x05 \x01(\x0b\x32\n.StartInfo2o\n\x02\x43U\x12\x38\n\rGetDefinition\x12\x16.google.protobuf.Empty\x1a\r.CUDefinition\"\x00\x12/\n\x05Start\x12\x0c.CUStartInfo\x1a\x16.google.protobuf.Empty\"\x00\x32u\n\x02\x44U\x12>\n\rGetDefinition\x12\x1c.google.protobuf.UInt32Value\x1a\r.DUDefinition\"\x00\x12/\n\x05Start\x12\x0c.DUStartInfo\x1a\x16.google.protobuf.Empty\"\x00\x32w\n\x03GNB\x12>\n\rGetDefinition\x12\x1c.google.protobuf.UInt32Value\x1a\r.DUDefinition\"\x00\x12\x30\n\x05Start\x12\r.GNBStartInfo\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retina.protocol.gnb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTARTINFO']._serialized_start=118
  _globals['_CUSTARTINFO']._serialized_end=230
  _globals['_DUSTARTINFO']._serialized_start=233
  _globals['_DUSTARTINFO']._serialized_end=480
  _globals['_GNBSTARTINFO']._serialized_start=483
  _globals['_GNBSTARTINFO']._serialized_end=680
  _globals['_CU']._serialized_start=682
  _globals['_CU']._serialized_end=793
  _globals['_DU']._serialized_start=795
  _globals['_DU']._serialized_end=912
  _globals['_GNB']._serialized_start=914
  _globals['_GNB']._serialized_end=1033
# @@protoc_insertion_point(module_scope)
