# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from retina.protocol import base_pb2 as retina_dot_protocol_dot_base__pb2
from retina.protocol import gnb_pb2 as retina_dot_protocol_dot_gnb__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in retina/protocol/gnb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CUStub(object):
    """CU service manages the Centralized Unit of the gNB split architecture
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDefinition = channel.unary_unary(
                '/CU/GetDefinition',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_base__pb2.CUDefinition.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/CU/Start',
                request_serializer=retina_dot_protocol_dot_gnb__pb2.CUStartInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CUServicer(object):
    """CU service manages the Centralized Unit of the gNB split architecture
    """

    def GetDefinition(self, request, context):
        """Get Basic information about the CU, like public ip or IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Start the CU. Raise an error if can't be started.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CUServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefinition,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=retina_dot_protocol_dot_base__pb2.CUDefinition.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=retina_dot_protocol_dot_gnb__pb2.CUStartInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CU', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CU', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CU(object):
    """CU service manages the Centralized Unit of the gNB split architecture
    """

    @staticmethod
    def GetDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CU/GetDefinition',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            retina_dot_protocol_dot_base__pb2.CUDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CU/Start',
            retina_dot_protocol_dot_gnb__pb2.CUStartInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DUStub(object):
    """DU service manages the Distributed Unit of the gNB split architecture
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDefinition = channel.unary_unary(
                '/DU/GetDefinition',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_base__pb2.DUDefinition.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/DU/Start',
                request_serializer=retina_dot_protocol_dot_gnb__pb2.DUStartInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class DUServicer(object):
    """DU service manages the Distributed Unit of the gNB split architecture
    """

    def GetDefinition(self, request, context):
        """Get Basic information about the DU, like public ip or IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Start the DU. Raise an error if can't be started.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DUServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefinition,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
                    response_serializer=retina_dot_protocol_dot_base__pb2.DUDefinition.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=retina_dot_protocol_dot_gnb__pb2.DUStartInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DU', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DU', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DU(object):
    """DU service manages the Distributed Unit of the gNB split architecture
    """

    @staticmethod
    def GetDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DU/GetDefinition',
            google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
            retina_dot_protocol_dot_base__pb2.DUDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DU/Start',
            retina_dot_protocol_dot_gnb__pb2.DUStartInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GNBStub(object):
    """GNB service manages the monolithic gNodeB base station
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDefinition = channel.unary_unary(
                '/GNB/GetDefinition',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_base__pb2.DUDefinition.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/GNB/Start',
                request_serializer=retina_dot_protocol_dot_gnb__pb2.GNBStartInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class GNBServicer(object):
    """GNB service manages the monolithic gNodeB base station
    """

    def GetDefinition(self, request, context):
        """Get Basic information about the GNB, like public ip or IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Start the GNB. Raise an error if can't be started.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GNBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefinition,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
                    response_serializer=retina_dot_protocol_dot_base__pb2.DUDefinition.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=retina_dot_protocol_dot_gnb__pb2.GNBStartInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GNB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GNB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GNB(object):
    """GNB service manages the monolithic gNodeB base station
    """

    @staticmethod
    def GetDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GNB/GetDefinition',
            google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
            retina_dot_protocol_dot_base__pb2.DUDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GNB/Start',
            retina_dot_protocol_dot_gnb__pb2.GNBStartInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
