# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
SPDX-License-Identifier: BSD-3-Clause-Open-MPI
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import retina.protocol.base_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CUStartInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLMN_FIELD_NUMBER: builtins.int
    FIVEGC_DEFINITION_FIELD_NUMBER: builtins.int
    START_INFO_FIELD_NUMBER: builtins.int
    @property
    def plmn(self) -> retina.protocol.base_pb2.PLMN: ...
    @property
    def fivegc_definition(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[retina.protocol.base_pb2.FiveGCDefinition]: ...
    @property
    def start_info(self) -> retina.protocol.base_pb2.StartInfo: ...
    def __init__(
        self,
        *,
        plmn: retina.protocol.base_pb2.PLMN | None = ...,
        fivegc_definition: collections.abc.Iterable[retina.protocol.base_pb2.FiveGCDefinition] | None = ...,
        start_info: retina.protocol.base_pb2.StartInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["plmn", b"plmn", "start_info", b"start_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fivegc_definition", b"fivegc_definition", "plmn", b"plmn", "start_info", b"start_info"]) -> None: ...

Global___CUStartInfo: typing_extensions.TypeAlias = CUStartInfo

@typing.final
class DUStartInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GNB_DU_ID_FIELD_NUMBER: builtins.int
    PLMN_FIELD_NUMBER: builtins.int
    NUM_CELLS_FIELD_NUMBER: builtins.int
    CELL_OFFSET_FIELD_NUMBER: builtins.int
    CU_DEFINITION_FIELD_NUMBER: builtins.int
    UE_DEFINITION_FIELD_NUMBER: builtins.int
    RIC_DEFINITION_FIELD_NUMBER: builtins.int
    START_INFO_FIELD_NUMBER: builtins.int
    gnb_du_id: builtins.int
    num_cells: builtins.int
    cell_offset: builtins.int
    @property
    def plmn(self) -> retina.protocol.base_pb2.PLMN: ...
    @property
    def cu_definition(self) -> retina.protocol.base_pb2.CUDefinition: ...
    @property
    def ue_definition(self) -> retina.protocol.base_pb2.UEDefinition:
        """Only required in ZMQ mode"""

    @property
    def ric_definition(self) -> retina.protocol.base_pb2.NearRtRicDefinition:
        """if non-empty, E2 is enabled"""

    @property
    def start_info(self) -> retina.protocol.base_pb2.StartInfo: ...
    def __init__(
        self,
        *,
        gnb_du_id: builtins.int = ...,
        plmn: retina.protocol.base_pb2.PLMN | None = ...,
        num_cells: builtins.int = ...,
        cell_offset: builtins.int = ...,
        cu_definition: retina.protocol.base_pb2.CUDefinition | None = ...,
        ue_definition: retina.protocol.base_pb2.UEDefinition | None = ...,
        ric_definition: retina.protocol.base_pb2.NearRtRicDefinition | None = ...,
        start_info: retina.protocol.base_pb2.StartInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["cu_definition", b"cu_definition", "plmn", b"plmn", "ric_definition", b"ric_definition", "start_info", b"start_info", "ue_definition", b"ue_definition"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cell_offset", b"cell_offset", "cu_definition", b"cu_definition", "gnb_du_id", b"gnb_du_id", "num_cells", b"num_cells", "plmn", b"plmn", "ric_definition", b"ric_definition", "start_info", b"start_info", "ue_definition", b"ue_definition"]) -> None: ...

Global___DUStartInfo: typing_extensions.TypeAlias = DUStartInfo

@typing.final
class GNBStartInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLMN_FIELD_NUMBER: builtins.int
    FIVEGC_DEFINITION_FIELD_NUMBER: builtins.int
    UE_DEFINITION_FIELD_NUMBER: builtins.int
    RIC_DEFINITION_FIELD_NUMBER: builtins.int
    START_INFO_FIELD_NUMBER: builtins.int
    @property
    def plmn(self) -> retina.protocol.base_pb2.PLMN: ...
    @property
    def fivegc_definition(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[retina.protocol.base_pb2.FiveGCDefinition]: ...
    @property
    def ue_definition(self) -> retina.protocol.base_pb2.UEDefinition:
        """Only required in ZMQ mode"""

    @property
    def ric_definition(self) -> retina.protocol.base_pb2.NearRtRicDefinition:
        """if non-empty, E2 is enabled"""

    @property
    def start_info(self) -> retina.protocol.base_pb2.StartInfo: ...
    def __init__(
        self,
        *,
        plmn: retina.protocol.base_pb2.PLMN | None = ...,
        fivegc_definition: collections.abc.Iterable[retina.protocol.base_pb2.FiveGCDefinition] | None = ...,
        ue_definition: retina.protocol.base_pb2.UEDefinition | None = ...,
        ric_definition: retina.protocol.base_pb2.NearRtRicDefinition | None = ...,
        start_info: retina.protocol.base_pb2.StartInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["plmn", b"plmn", "ric_definition", b"ric_definition", "start_info", b"start_info", "ue_definition", b"ue_definition"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fivegc_definition", b"fivegc_definition", "plmn", b"plmn", "ric_definition", b"ric_definition", "start_info", b"start_info", "ue_definition", b"ue_definition"]) -> None: ...

Global___GNBStartInfo: typing_extensions.TypeAlias = GNBStartInfo
