#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retina/protocol/ric.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'retina/protocol/ric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from retina.protocol import base_pb2 as retina_dot_protocol_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19retina/protocol/ric.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1aretina/protocol/base.proto\"4\n\x12NearRtRicStartInfo\x12\x1e\n\nstart_info\x18\x01 \x01(\x0b\x32\n.StartInfo\"Q\n\x11KpmMonXappRequest\x12\x1c\n\x14report_service_style\x18\x01 \x01(\r\x12\r\n\x05ue_id\x18\x02 \x01(\r\x12\x0f\n\x07metrics\x18\x03 \x01(\t\"/\n\x10\x43ontrolParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"\xbb\x01\n\rRcXappRequest\x12\x1d\n\x15\x63ontrol_service_style\x18\x01 \x01(\r\x12\x11\n\taction_id\x18\x02 \x01(\r\x12\x32\n\nparameters\x18\x03 \x03(\x0b\x32\x1e.RcXappRequest.ParametersEntry\x1a\x44\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.ControlParameter:\x02\x38\x01\"\xdb\x01\n\x10NearRtRicSummary\x12\x1c\n\x14nof_connected_agents\x18\x01 \x01(\r\x12\x1b\n\x13nof_connected_xapps\x18\x02 \x01(\r\x12\x1d\n\x15nof_subscription_reqs\x18\x03 \x01(\r\x12\x1d\n\x15nof_subscription_reps\x18\x04 \x01(\r\x12\x1a\n\x12nof_ric_indication\x18\x05 \x01(\r\x12\x18\n\x10nof_control_reqs\x18\x06 \x01(\r\x12\x18\n\x10nof_control_reps\x18\x07 \x01(\r2\xc6\x03\n\tNearRtRic\x12?\n\rGetDefinition\x12\x16.google.protobuf.Empty\x1a\x14.NearRtRicDefinition\"\x00\x12\x36\n\x05Start\x12\x13.NearRtRicStartInfo\x1a\x16.google.protobuf.Empty\"\x00\x12?\n\x0fStartKpmMonXapp\x12\x12.KpmMonXappRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x42\n\x0eStopKpmMonXapp\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x37\n\x0bStartRcXapp\x12\x0e.RcXappRequest\x1a\x16.google.protobuf.Empty\"\x00\x12>\n\nStopRcXapp\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x42\n\x13GetNearRtRicSummary\x12\x16.google.protobuf.Empty\x1a\x11.NearRtRicSummary\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retina.protocol.ric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RCXAPPREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_RCXAPPREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_NEARRTRICSTARTINFO']._serialized_start=86
  _globals['_NEARRTRICSTARTINFO']._serialized_end=138
  _globals['_KPMMONXAPPREQUEST']._serialized_start=140
  _globals['_KPMMONXAPPREQUEST']._serialized_end=221
  _globals['_CONTROLPARAMETER']._serialized_start=223
  _globals['_CONTROLPARAMETER']._serialized_end=270
  _globals['_RCXAPPREQUEST']._serialized_start=273
  _globals['_RCXAPPREQUEST']._serialized_end=460
  _globals['_RCXAPPREQUEST_PARAMETERSENTRY']._serialized_start=392
  _globals['_RCXAPPREQUEST_PARAMETERSENTRY']._serialized_end=460
  _globals['_NEARRTRICSUMMARY']._serialized_start=463
  _globals['_NEARRTRICSUMMARY']._serialized_end=682
  _globals['_NEARRTRIC']._serialized_start=685
  _globals['_NEARRTRIC']._serialized_end=1139
# @@protoc_insertion_point(module_scope)
