"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file


Copyright 2021-2026 Software Radio Systems Limited

By using this file, you agree to the terms and conditions set
forth in the LICENSE file which can be found at the top level of
the distribution.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import retina.protocol.base_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class NearRtRicStartInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_INFO_FIELD_NUMBER: builtins.int
    @property
    def start_info(self) -> retina.protocol.base_pb2.StartInfo: ...
    def __init__(
        self,
        *,
        start_info: retina.protocol.base_pb2.StartInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["start_info", b"start_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["start_info", b"start_info"]) -> None: ...

Global___NearRtRicStartInfo: typing_extensions.TypeAlias = NearRtRicStartInfo

@typing.final
class KpmMonXappRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPORT_SERVICE_STYLE_FIELD_NUMBER: builtins.int
    UE_ID_FIELD_NUMBER: builtins.int
    METRICS_FIELD_NUMBER: builtins.int
    report_service_style: builtins.int
    ue_id: builtins.int
    metrics: builtins.str
    def __init__(
        self,
        *,
        report_service_style: builtins.int = ...,
        ue_id: builtins.int = ...,
        metrics: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["metrics", b"metrics", "report_service_style", b"report_service_style", "ue_id", b"ue_id"]) -> None: ...

Global___KpmMonXappRequest: typing_extensions.TypeAlias = KpmMonXappRequest

@typing.final
class ControlParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: builtins.str
    value: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "value", b"value"]) -> None: ...

Global___ControlParameter: typing_extensions.TypeAlias = ControlParameter

@typing.final
class RcXappRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ParametersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> Global___ControlParameter: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: Global___ControlParameter | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    CONTROL_SERVICE_STYLE_FIELD_NUMBER: builtins.int
    ACTION_ID_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    control_service_style: builtins.int
    action_id: builtins.int
    @property
    def parameters(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, Global___ControlParameter]: ...
    def __init__(
        self,
        *,
        control_service_style: builtins.int = ...,
        action_id: builtins.int = ...,
        parameters: collections.abc.Mapping[builtins.int, Global___ControlParameter] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action_id", b"action_id", "control_service_style", b"control_service_style", "parameters", b"parameters"]) -> None: ...

Global___RcXappRequest: typing_extensions.TypeAlias = RcXappRequest

@typing.final
class NearRtRicSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NOF_CONNECTED_AGENTS_FIELD_NUMBER: builtins.int
    NOF_CONNECTED_XAPPS_FIELD_NUMBER: builtins.int
    NOF_SUBSCRIPTION_REQS_FIELD_NUMBER: builtins.int
    NOF_SUBSCRIPTION_REPS_FIELD_NUMBER: builtins.int
    NOF_RIC_INDICATION_FIELD_NUMBER: builtins.int
    NOF_CONTROL_REQS_FIELD_NUMBER: builtins.int
    NOF_CONTROL_REPS_FIELD_NUMBER: builtins.int
    nof_connected_agents: builtins.int
    nof_connected_xapps: builtins.int
    nof_subscription_reqs: builtins.int
    nof_subscription_reps: builtins.int
    nof_ric_indication: builtins.int
    nof_control_reqs: builtins.int
    nof_control_reps: builtins.int
    def __init__(
        self,
        *,
        nof_connected_agents: builtins.int = ...,
        nof_connected_xapps: builtins.int = ...,
        nof_subscription_reqs: builtins.int = ...,
        nof_subscription_reps: builtins.int = ...,
        nof_ric_indication: builtins.int = ...,
        nof_control_reqs: builtins.int = ...,
        nof_control_reps: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nof_connected_agents", b"nof_connected_agents", "nof_connected_xapps", b"nof_connected_xapps", "nof_control_reps", b"nof_control_reps", "nof_control_reqs", b"nof_control_reqs", "nof_ric_indication", b"nof_ric_indication", "nof_subscription_reps", b"nof_subscription_reps", "nof_subscription_reqs", b"nof_subscription_reqs"]) -> None: ...

Global___NearRtRicSummary: typing_extensions.TypeAlias = NearRtRicSummary
