# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from retina.protocol import base_pb2 as retina_dot_protocol_dot_base__pb2
from retina.protocol import ue_pb2 as retina_dot_protocol_dot_ue__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in retina/protocol/ue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UEStub(object):
    """UE service manages user equipment operations including attachment, movement, and traffic generation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDefinition = channel.unary_unary(
                '/UE/GetDefinition',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_base__pb2.UEDefinition.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/UE/Start',
                request_serializer=retina_dot_protocol_dot_ue__pb2.UEStartInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.WaitUntilAttached = channel.unary_unary(
                '/UE/WaitUntilAttached',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_ue__pb2.UEAttachedInfo.FromString,
                _registered_method=True)
        self.WaitUntilReleased = channel.unary_unary(
                '/UE/WaitUntilReleased',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.IPerf = channel.unary_unary(
                '/UE/IPerf',
                request_serializer=retina_dot_protocol_dot_ue__pb2.IPerfRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Reestablishment = channel.unary_unary(
                '/UE/Reestablishment',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_ue__pb2.ReestablishmentInfo.FromString,
                _registered_method=True)
        self.Move = channel.unary_unary(
                '/UE/Move',
                request_serializer=retina_dot_protocol_dot_ue__pb2.Position.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ExpectHandover = channel.unary_unary(
                '/UE/ExpectHandover',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_ue__pb2.HandoverInfo.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/UE/GetMessages',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=retina_dot_protocol_dot_ue__pb2.RrcMessages.FromString,
                _registered_method=True)


class UEServicer(object):
    """UE service manages user equipment operations including attachment, movement, and traffic generation
    """

    def GetDefinition(self, request, context):
        """Get Basic information about the UE, like public ip or IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Start the UE. Raise an error if can't be started.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitUntilAttached(self, request, context):
        """Wait until attached. Raised an TimeoutError if timeout is reached
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitUntilReleased(self, request, context):
        """Wait until released. Raised an TimeoutError if timeout is reached
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IPerf(self, request, context):
        """Run a iperf
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reestablishment(self, request, context):
        """Run a reestablishment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Move the simulated UE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpectHandover(self, request, context):
        """Expect a Handover
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Get messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UEServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefinition,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=retina_dot_protocol_dot_base__pb2.UEDefinition.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=retina_dot_protocol_dot_ue__pb2.UEStartInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'WaitUntilAttached': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitUntilAttached,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
                    response_serializer=retina_dot_protocol_dot_ue__pb2.UEAttachedInfo.SerializeToString,
            ),
            'WaitUntilReleased': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitUntilReleased,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'IPerf': grpc.unary_unary_rpc_method_handler(
                    servicer.IPerf,
                    request_deserializer=retina_dot_protocol_dot_ue__pb2.IPerfRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Reestablishment': grpc.unary_unary_rpc_method_handler(
                    servicer.Reestablishment,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
                    response_serializer=retina_dot_protocol_dot_ue__pb2.ReestablishmentInfo.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=retina_dot_protocol_dot_ue__pb2.Position.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ExpectHandover': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpectHandover,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
                    response_serializer=retina_dot_protocol_dot_ue__pb2.HandoverInfo.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=retina_dot_protocol_dot_ue__pb2.RrcMessages.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UE', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UE', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UE(object):
    """UE service manages user equipment operations including attachment, movement, and traffic generation
    """

    @staticmethod
    def GetDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UE/GetDefinition',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            retina_dot_protocol_dot_base__pb2.UEDefinition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UE/Start',
            retina_dot_protocol_dot_ue__pb2.UEStartInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitUntilAttached(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UE/WaitUntilAttached',
            google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
            retina_dot_protocol_dot_ue__pb2.UEAttachedInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitUntilReleased(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UE/WaitUntilReleased',
            google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IPerf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UE/IPerf',
            retina_dot_protocol_dot_ue__pb2.IPerfRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reestablishment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UE/Reestablishment',
            google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
            retina_dot_protocol_dot_ue__pb2.ReestablishmentInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UE/Move',
            retina_dot_protocol_dot_ue__pb2.Position.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpectHandover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UE/ExpectHandover',
            google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
            retina_dot_protocol_dot_ue__pb2.HandoverInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UE/GetMessages',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            retina_dot_protocol_dot_ue__pb2.RrcMessages.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
