"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file


Copyright 2021-2026 Software Radio Systems Limited

By using this file, you agree to the terms and conditions set
forth in the LICENSE file which can be found at the top level of
the distribution.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import retina.protocol.base_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _IPerfDir:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IPerfDirEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IPerfDir.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UPLINK: _IPerfDir.ValueType  # 0
    DOWNLINK: _IPerfDir.ValueType  # 1
    BIDIRECTIONAL: _IPerfDir.ValueType  # 2

class IPerfDir(_IPerfDir, metaclass=_IPerfDirEnumTypeWrapper): ...

UPLINK: IPerfDir.ValueType  # 0
DOWNLINK: IPerfDir.ValueType  # 1
BIDIRECTIONAL: IPerfDir.ValueType  # 2
Global___IPerfDir: typing_extensions.TypeAlias = IPerfDir

class _IPerfProto:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IPerfProtoEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IPerfProto.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TCP: _IPerfProto.ValueType  # 0
    UDP: _IPerfProto.ValueType  # 1

class IPerfProto(_IPerfProto, metaclass=_IPerfProtoEnumTypeWrapper): ...

TCP: IPerfProto.ValueType  # 0
UDP: IPerfProto.ValueType  # 1
Global___IPerfProto: typing_extensions.TypeAlias = IPerfProto

@typing.final
class UEStartInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DU_DEFINITION_FIELD_NUMBER: builtins.int
    FIVEGC_DEFINITION_FIELD_NUMBER: builtins.int
    START_INFO_FIELD_NUMBER: builtins.int
    @property
    def du_definition(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[retina.protocol.base_pb2.DUDefinition]:
        """Only required in ZMQ mode"""

    @property
    def fivegc_definition(self) -> retina.protocol.base_pb2.FiveGCDefinition:
        """Only required for CotsUEs"""

    @property
    def start_info(self) -> retina.protocol.base_pb2.StartInfo: ...
    def __init__(
        self,
        *,
        du_definition: collections.abc.Iterable[retina.protocol.base_pb2.DUDefinition] | None = ...,
        fivegc_definition: retina.protocol.base_pb2.FiveGCDefinition | None = ...,
        start_info: retina.protocol.base_pb2.StartInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fivegc_definition", b"fivegc_definition", "start_info", b"start_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["du_definition", b"du_definition", "fivegc_definition", b"fivegc_definition", "start_info", b"start_info"]) -> None: ...

Global___UEStartInfo: typing_extensions.TypeAlias = UEStartInfo

@typing.final
class UEAttachedInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UE_ID_FIELD_NUMBER: builtins.int
    PDN_ID_FIELD_NUMBER: builtins.int
    INTERFACE_FIELD_NUMBER: builtins.int
    IPV4_FIELD_NUMBER: builtins.int
    IPV4_DNS_FIELD_NUMBER: builtins.int
    IPV4_GATEWAY_FIELD_NUMBER: builtins.int
    IPV6_FIELD_NUMBER: builtins.int
    IPV6_DNS_FIELD_NUMBER: builtins.int
    IPV6_GATEWAY_FIELD_NUMBER: builtins.int
    RNTI_FIELD_NUMBER: builtins.int
    ue_id: builtins.int
    pdn_id: builtins.str
    interface: builtins.str
    ipv4: builtins.str
    ipv4_dns: builtins.str
    ipv4_gateway: builtins.str
    ipv6: builtins.str
    ipv6_dns: builtins.str
    ipv6_gateway: builtins.str
    rnti: builtins.int
    def __init__(
        self,
        *,
        ue_id: builtins.int = ...,
        pdn_id: builtins.str = ...,
        interface: builtins.str = ...,
        ipv4: builtins.str = ...,
        ipv4_dns: builtins.str = ...,
        ipv4_gateway: builtins.str = ...,
        ipv6: builtins.str = ...,
        ipv6_dns: builtins.str = ...,
        ipv6_gateway: builtins.str = ...,
        rnti: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["interface", b"interface", "ipv4", b"ipv4", "ipv4_dns", b"ipv4_dns", "ipv4_gateway", b"ipv4_gateway", "ipv6", b"ipv6", "ipv6_dns", b"ipv6_dns", "ipv6_gateway", b"ipv6_gateway", "pdn_id", b"pdn_id", "rnti", b"rnti", "ue_id", b"ue_id"]) -> None: ...

Global___UEAttachedInfo: typing_extensions.TypeAlias = UEAttachedInfo

@typing.final
class IPerfRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    PROTO_FIELD_NUMBER: builtins.int
    BITRATE_FIELD_NUMBER: builtins.int
    PACKET_LENGTH_FIELD_NUMBER: builtins.int
    TOS_FIELD_NUMBER: builtins.int
    duration: builtins.int
    direction: Global___IPerfDir.ValueType
    proto: Global___IPerfProto.ValueType
    bitrate: builtins.int
    packet_length: builtins.int
    tos: builtins.int
    @property
    def server(self) -> retina.protocol.base_pb2.IPerfServer: ...
    def __init__(
        self,
        *,
        server: retina.protocol.base_pb2.IPerfServer | None = ...,
        duration: builtins.int = ...,
        direction: Global___IPerfDir.ValueType = ...,
        proto: Global___IPerfProto.ValueType = ...,
        bitrate: builtins.int = ...,
        packet_length: builtins.int = ...,
        tos: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["server", b"server"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bitrate", b"bitrate", "direction", b"direction", "duration", b"duration", "packet_length", b"packet_length", "proto", b"proto", "server", b"server", "tos", b"tos"]) -> None: ...

Global___IPerfRequest: typing_extensions.TypeAlias = IPerfRequest

@typing.final
class Position(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y", "z", b"z"]) -> None: ...

Global___Position: typing_extensions.TypeAlias = Position

@typing.final
class RrcMessages(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NOF_SETUP_FIELD_NUMBER: builtins.int
    NOF_REESTABLISHMENT_COMPLETE_FIELD_NUMBER: builtins.int
    NOF_RECONFIGURATION_FIELD_NUMBER: builtins.int
    NOF_RECONFIGURATION_COMPLETE_FIELD_NUMBER: builtins.int
    nof_setup: builtins.int
    nof_reestablishment_complete: builtins.int
    nof_reconfiguration: builtins.int
    nof_reconfiguration_complete: builtins.int
    def __init__(
        self,
        *,
        nof_setup: builtins.int = ...,
        nof_reestablishment_complete: builtins.int = ...,
        nof_reconfiguration: builtins.int = ...,
        nof_reconfiguration_complete: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["nof_reconfiguration", b"nof_reconfiguration", "nof_reconfiguration_complete", b"nof_reconfiguration_complete", "nof_reestablishment_complete", b"nof_reestablishment_complete", "nof_setup", b"nof_setup"]) -> None: ...

Global___RrcMessages: typing_extensions.TypeAlias = RrcMessages

@typing.final
class ReestablishmentInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    PREVIOUS_MESSAGES_FIELD_NUMBER: builtins.int
    LAST_MESSAGES_FIELD_NUMBER: builtins.int
    status: builtins.bool
    @property
    def previous_messages(self) -> Global___RrcMessages: ...
    @property
    def last_messages(self) -> Global___RrcMessages: ...
    def __init__(
        self,
        *,
        status: builtins.bool = ...,
        previous_messages: Global___RrcMessages | None = ...,
        last_messages: Global___RrcMessages | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["last_messages", b"last_messages", "previous_messages", b"previous_messages"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["last_messages", b"last_messages", "previous_messages", b"previous_messages", "status", b"status"]) -> None: ...

Global___ReestablishmentInfo: typing_extensions.TypeAlias = ReestablishmentInfo

@typing.final
class HandoverInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    PREVIOUS_PCI_FIELD_NUMBER: builtins.int
    LAST_PCI_FIELD_NUMBER: builtins.int
    PREVIOUS_MESSAGES_FIELD_NUMBER: builtins.int
    LAST_MESSAGES_FIELD_NUMBER: builtins.int
    status: builtins.bool
    previous_pci: builtins.int
    last_pci: builtins.int
    @property
    def previous_messages(self) -> Global___RrcMessages: ...
    @property
    def last_messages(self) -> Global___RrcMessages: ...
    def __init__(
        self,
        *,
        status: builtins.bool = ...,
        previous_pci: builtins.int = ...,
        last_pci: builtins.int = ...,
        previous_messages: Global___RrcMessages | None = ...,
        last_messages: Global___RrcMessages | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["last_messages", b"last_messages", "previous_messages", b"previous_messages"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["last_messages", b"last_messages", "last_pci", b"last_pci", "previous_messages", b"previous_messages", "previous_pci", b"previous_pci", "status", b"status"]) -> None: ...

Global___HandoverInfo: typing_extensions.TypeAlias = HandoverInfo
