# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retina/protocol/ue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'retina/protocol/ue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from retina.protocol import base_pb2 as retina_dot_protocol_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18retina/protocol/ue.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1aretina/protocol/base.proto\"\x81\x01\n\x0bUEStartInfo\x12$\n\rdu_definition\x18\x01 \x03(\x0b\x32\r.DUDefinition\x12,\n\x11\x66ivegc_definition\x18\x02 \x03(\x0b\x32\x11.FiveGCDefinition\x12\x1e\n\nstart_info\x18\x03 \x01(\x0b\x32\n.StartInfo\"\xbc\x01\n\x0eUEAttachedInfo\x12\r\n\x05ue_id\x18\x01 \x01(\r\x12\x0e\n\x06pdn_id\x18\x02 \x01(\t\x12\x11\n\tinterface\x18\x03 \x01(\t\x12\x0c\n\x04ipv4\x18\x04 \x01(\t\x12\x10\n\x08ipv4_dns\x18\x05 \x01(\t\x12\x14\n\x0cipv4_gateway\x18\x06 \x01(\t\x12\x0c\n\x04ipv6\x18\x07 \x01(\t\x12\x10\n\x08ipv6_dns\x18\x08 \x01(\t\x12\x14\n\x0cipv6_gateway\x18\t \x01(\t\x12\x0c\n\x04rnti\x18\n \x01(\r\"\xad\x01\n\x0cIPerfRequest\x12\x1c\n\x06server\x18\x01 \x01(\x0b\x32\x0c.IPerfServer\x12\x10\n\x08\x64uration\x18\x02 \x01(\x04\x12\x1c\n\tdirection\x18\x03 \x01(\x0e\x32\t.IPerfDir\x12\x1a\n\x05proto\x18\x04 \x01(\x0e\x32\x0b.IPerfProto\x12\x0f\n\x07\x62itrate\x18\x05 \x01(\x04\x12\x15\n\rpacket_length\x18\x06 \x01(\r\x12\x0b\n\x03tos\x18\x07 \x01(\r\"+\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01*7\n\x08IPerfDir\x12\n\n\x06UPLINK\x10\x00\x12\x0c\n\x08\x44OWNLINK\x10\x01\x12\x11\n\rBIDIRECTIONAL\x10\x02*\x1e\n\nIPerfProto\x12\x07\n\x03TCP\x10\x00\x12\x07\n\x03UDP\x10\x01\x32\xe7\x01\n\x02UE\x12\x38\n\rGetDefinition\x12\x16.google.protobuf.Empty\x1a\r.UEDefinition\"\x00\x12/\n\x05Start\x12\x0c.UEStartInfo\x1a\x16.google.protobuf.Empty\"\x00\x12\x44\n\x11WaitUntilAttached\x12\x1c.google.protobuf.UInt32Value\x1a\x0f.UEAttachedInfo\"\x00\x12\x30\n\x05IPerf\x12\r.IPerfRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retina.protocol.ue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IPERFDIR']._serialized_start=661
  _globals['_IPERFDIR']._serialized_end=716
  _globals['_IPERFPROTO']._serialized_start=718
  _globals['_IPERFPROTO']._serialized_end=748
  _globals['_UESTARTINFO']._serialized_start=118
  _globals['_UESTARTINFO']._serialized_end=247
  _globals['_UEATTACHEDINFO']._serialized_start=250
  _globals['_UEATTACHEDINFO']._serialized_end=438
  _globals['_IPERFREQUEST']._serialized_start=441
  _globals['_IPERFREQUEST']._serialized_end=614
  _globals['_POSITION']._serialized_start=616
  _globals['_POSITION']._serialized_end=659
  _globals['_UE']._serialized_start=751
  _globals['_UE']._serialized_end=982
# @@protoc_insertion_point(module_scope)
