# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/python.yml

stages:
  - static
  - publish

.orchestrator_build_dependencies:
  before_script:
    - |
      . /etc/os-release

      echo "Setting up the OS"
      case "$ID" in
        debian | ubuntu) DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends build-essential libffi-dev ;;
                 alpine) apk add build-base linux-headers libffi-dev ;;
                      *) echo 'Unsupported OS' && exit 1 ;;
      esac
  variables:
    PY_DIR: retina/orchestrator

tox:
  stage: static
  extends:
    - .orchestrator_build_dependencies
    - .tox

publish deps:
  stage: publish
  extends:
    - .orchestrator_build_dependencies
    - .publish deps

publish wheel:
  stage: publish
  extends:
    - .orchestrator_build_dependencies
    - .publish wheel
