# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

"""
Executor: run process in local, remote, etc.
"""

import logging
import os
import queue
import shutil
import signal
import sys
import warnings
from abc import ABCMeta, abstractmethod
from asyncio import subprocess
from base64 import b64decode
from contextlib import contextmanager, suppress
from pathlib import Path
from threading import Thread
from time import sleep, time
from typing import Any, Generator, Iterator, List, Optional, Protocol, TextIO, Tuple, Union

import psutil
from cryptography.utils import CryptographyDeprecationWarning

from retina.agent.parameters import testbed_defaults
from retina.agent.tools.time import now_timestamp_file, TimeoutHandler

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=CryptographyDeprecationWarning)
    import paramiko


class ProcessLike(Protocol):
    """Minimal process interface used by exit_process / is_process_alive."""

    @property
    def pid(self) -> int:
        """Process ID."""

    def name(self) -> str:
        """Return the process name."""

    def wait(self, timeout: Optional[float] = ...) -> Optional[int]:
        """Wait for process termination; raise TimeoutExpired if timeout elapses."""

    def send_signal(self, sig: int) -> None:
        """Send signal sig to the process."""

    def kill(self) -> None:
        """Kill the process with SIGKILL."""


class SutProcessLike(ProcessLike, Protocol):
    """Full process interface returned by create_process."""

    returncode: Optional[int]
    stdin: Any
    stdout: Any

    def children(self, recursive: bool = ...) -> List[Any]:
        """Return child processes."""

    def is_running(self) -> bool:
        """Return True if the process is still running."""


class Executor(metaclass=ABCMeta):
    """
    Executor: run process in local, remote, etc.
    """

    @abstractmethod
    def copy_file(
        self,
        path: Union[str, Path],
        destiny: Union[str, Path],
        is_remote_file: bool = False,
    ) -> None:
        """
        Copy a file or a folder
        """

    @abstractmethod
    def mkdir(self, path: Union[str, Path]) -> None:
        """
        Creates a folder
        """

    @abstractmethod
    def close_folder(self, path: Union[str, Path]) -> None:
        """
        The folder won't be used anymore
        """

    @abstractmethod
    def write_file(self, path: Union[str, Path], content: str) -> None:
        """
        Write to a file
        """

    @abstractmethod
    def run_binary(
        self,
        *cmd: str,
        keeplinebreaks: bool = False,
        timeout: Optional[float] = None,
        raise_if_exit_code: bool = True,
    ) -> Iterator[str]:
        """
        Runs a process with specified cmd args.
        It yields each stdout line generated by the process.
        If the timeout is reached, it will raise a TimeoutException.
        If it ends with an exit code rather than 0, a ChildProcessError is raised.
        """

    @abstractmethod
    def create_process(
        self, *cmd: str, logfile: Optional[TextIO] = None, extra_env: Optional[dict] = None
    ) -> SutProcessLike:
        """
        Creates a process and returns it.
        """

    @abstractmethod
    def find_in_path(self, binary_name: str) -> str:
        """
        Return absolute path of a `binary_name` in the $PATH.
        :param binary_name
        :return str
        """

    @abstractmethod
    def read_from_process_stdout(
        self,
        process: SutProcessLike,
        keeplinebreaks: bool = False,
        timeout: Optional[float] = None,
    ) -> Iterator[str]:
        """
        It yields each stdout line generated by the process.
        If the timeout is reached, it will raise a TimeoutException.
        The process is not killed even if timeout is reached.
        """

    @abstractmethod
    def exit_process(
        self,
        process: ProcessLike,
        timeout: float = 5,
        stop_process_check_timeout: float = 0.5,
    ) -> int:
        """
        Stop a process.
        It tries to stop it with a signal. If timeout is reached, the process is killed.
        :param process
        :param timeout
        :return int: returncode
        """

    @abstractmethod
    def is_process_alive(self, process: Optional[ProcessLike]) -> bool:
        """
        Return if a process is running.
        :param process
        :return bool
        """


class LocalExecutor(Executor, metaclass=ABCMeta):
    """
    Run processes in local system
    """

    EXIT_PROCESS_TIMEOUT: int = 5
    _KILLED_EXIT_CODE: int = -9
    _READ_FROM_PROCESS_STEP: float = 0.1

    CONTROL_C_SIGNAL: int = getattr(signal, "CTRL_C_EVENT", signal.SIGTERM)

    def copy_file(
        self,
        path: Union[str, Path],
        destiny: Union[str, Path],
        is_remote_file: bool = False,
    ) -> None:
        if not is_remote_file:
            shutil.copy(path, destiny)

    def mkdir(self, path: Union[str, Path]) -> None:
        Path(path).resolve().mkdir(parents=True, exist_ok=False)

    def close_folder(self, path: Union[str, Path]) -> None:
        pass

    def write_file(self, path: Union[str, Path], content: str) -> None:
        with Path(path).resolve().open("w", encoding="utf-8") as dst_file_descriptor:
            dst_file_descriptor.write(content)

    def run_binary(
        self,
        *cmd: str,
        keeplinebreaks: bool = False,
        timeout: Optional[float] = None,
        raise_if_exit_code: bool = True,
    ) -> Iterator[str]:
        process = self.create_process(*cmd)
        try:
            yield from self.read_from_process_stdout(process, keeplinebreaks=keeplinebreaks, timeout=timeout)
        except TimeoutError as err:
            # If timeout error, we disable raising another exception
            raise_if_exit_code = False
            raise err from None
        finally:
            try:
                return_code = process.wait(0.1)
            except psutil.TimeoutExpired:
                return_code = self.exit_process(process)

            if return_code and raise_if_exit_code:
                raise ChildProcessError(return_code)

    def create_process(
        self, *cmd: str, logfile: Optional[TextIO] = None, extra_env: Optional[dict] = None
    ) -> SutProcessLike:
        """
        Creates a process and returns it.
        """
        binary_name, *binary_params = cmd
        process = psutil.Popen(
            (self.find_in_path(binary_name), *binary_params),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            universal_newlines=True,
            env={**os.environ, **extra_env} if extra_env else None,
        )
        if logfile is not None:
            Thread(target=_tee_output, args=(process.stdout, logfile, sys.stdout), daemon=True).start()
        return process

    def find_in_path(self, binary_name: str) -> str:
        if Path(binary_name).is_absolute() and Path(binary_name).exists():
            return binary_name
        path = shutil.which(binary_name)
        if path is None:
            raise FileNotFoundError(f"Can not found '{binary_name}' in path")
        return path

    def read_from_process_stdout(
        self,
        process: SutProcessLike,
        keeplinebreaks: bool = False,
        timeout: Optional[float] = None,
    ) -> Iterator[str]:
        """
        It yields each stdout line generated by the process.
        If the timeout is reached, it will raise a TimeoutException.
        The process is not killed even if timeout is reached.
        """
        queue_obj: queue.Queue[str] = queue.Queue()
        thread_obj = Thread(target=_enqueue_output, args=(process.stdout, queue_obj))
        timeout_handler = TimeoutHandler(timeout)
        thread_obj.start()

        while timeout_handler.not_reached() and (thread_obj.is_alive() or not queue_obj.empty()):
            with suppress(queue.Empty):
                line = _remove_non_printable(queue_obj.get(timeout=self._READ_FROM_PROCESS_STEP))
                if line.strip():
                    yield line + (os.linesep if keeplinebreaks else "")

    def exit_process(
        self,
        process: ProcessLike,
        timeout: float = EXIT_PROCESS_TIMEOUT,
        stop_process_check_timeout: float = 0.5,
    ) -> int:
        """
        Stop a process.
        It tries to stop it with a signal. If timeout is reached, the process is killed.
        :param process
        :param timeout
        :return int: returncode
        """
        process_name = ""
        with suppress(psutil.NoSuchProcess):
            process_name = process.name()

        with suppress(SystemError, psutil.NoSuchProcess, TimeoutError):
            # Windows can raise SystemError. psutil can raise NoSuchProcess.
            # It doesn't matter, next block will handle both cases.
            process.send_signal(self.CONTROL_C_SIGNAL)
            logging.info("SIGTERM sent to %s [PID %s]", process_name, process.pid)

            timeout_handler = TimeoutHandler(timeout)
            while timeout_handler.not_reached():
                with suppress(psutil.TimeoutExpired):
                    # If process is finished,
                    #   wait method ends without any exception and go to return
                    # If process finishes during waiting,
                    #   it will return.
                    # If timeout is reached,
                    #   it raises an exception (differs between psutil and subprocess!!!)
                    #   Is captured by suppress without breaking the loop.
                    return self._process_wait(process, stop_process_check_timeout)

        # Timeout reached

        # Save status by attaching GDB an getting the backtrace
        with suppress(FileNotFoundError, ChildProcessError, psutil.NoSuchProcess, TimeoutError):
            self.find_in_path("gdb")
            logging.warning(
                "%s could not stop in expected timeout [%s seconds]. Backtrace: \n%s",
                process_name,
                timeout,
                "\n".join(
                    self.run_binary(
                        "gdb", "-p", str(process.pid), "-batch", "-ex", "thread apply all bt", "-ex", "detach"
                    )
                ),
            )
            # Wait another timeout to let the process finish before killing it
            timeout_handler = TimeoutHandler(timeout)
            while timeout_handler.not_reached():
                with suppress(psutil.TimeoutExpired):
                    return self._process_wait(process, stop_process_check_timeout)

        # Kill
        with suppress(SystemError, psutil.NoSuchProcess):
            logging.warning("SIGKILL sent to %s [PID %s]", process_name, process.pid)
            process.kill()

        with suppress(psutil.TimeoutExpired):
            return self._process_wait(process, stop_process_check_timeout)

        return self._KILLED_EXIT_CODE

    @staticmethod
    def _process_wait(process: ProcessLike, stop_process_check_timeout: float) -> int:
        return_code = process.wait(stop_process_check_timeout)
        if return_code is None:
            # If the process is already terminated immediately return None
            return_code = 0
        return int(return_code)

    def is_process_alive(self, process: Optional[ProcessLike]) -> bool:
        """
        Return if a process is running.
        :param process
        :return bool
        """

        if process is None:
            return False

        try:
            process.wait(0.1)
            return False
        except psutil.TimeoutExpired:
            return True


def _enqueue_output(process_stdout, queue_obj):
    for line in iter(process_stdout.readline, ""):
        queue_obj.put(line)
    # When process is dead, iterator also ends and this method stops


def _tee_output(source, *targets):
    for line in iter(source.readline, ""):
        for target in targets:
            target.write(line)
            target.flush()


def _remove_non_printable(my_string: str) -> str:
    return my_string.encode("ascii", errors="ignore").decode().rstrip()


class AdbExecutor(LocalExecutor):
    """
    Android Handler
    """

    ADB_KEY_FILEPATH = ".android/adbkey"
    ADB_KEY_PERMISSIONS = 0o600

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self._adb_ready: bool = False

    def find_in_path(self, binary_name: str) -> str:
        return binary_name  # Skip path validation inside android phone

    def _check_and_update_adbkey(self):
        # do not restart ADB if no new key provided or identical key already exists
        if not testbed_defaults.adb_key:
            logging.debug("No ADB key provided. ADB will use existing key or generate a new one on start.")
            return
        adb_key_path = Path.home().joinpath(self.ADB_KEY_FILEPATH)
        if adb_key_path.exists():
            with open(adb_key_path, mode="rb") as current_key_file:
                if current_key_file.read() == b64decode(testbed_defaults.adb_key):
                    logging.debug("ADB key is up to date.")
                    return

        # kill ADB server
        local_executor = LocalExecutor()
        for line in local_executor.run_binary("adb", "kill-server"):
            logging.debug(line)

        # backup old key
        if adb_key_path.exists():
            backup_adb_key_path = Path.home().joinpath(self.ADB_KEY_FILEPATH + "_" + now_timestamp_file())
            adb_key_path.rename(backup_adb_key_path)
            logging.debug("Current adbkey backup as %s", backup_adb_key_path)

        # write new key
        logging.debug("Writing ADB key to %s", adb_key_path)
        adb_key_path.parent.mkdir(parents=True, exist_ok=True)
        adb_key_path.touch(mode=self.ADB_KEY_PERMISSIONS)
        adb_key_path.write_bytes(b64decode(testbed_defaults.adb_key))

        # start ADB server
        for line in local_executor.run_binary("adb", "start-server"):
            logging.debug(line)
        for line in local_executor.run_binary("adb", "devices"):
            logging.debug(line)

    def create_process(
        self, *cmd: str, logfile: Optional[TextIO] = None, extra_env: Optional[dict] = None
    ) -> SutProcessLike:
        logging.info("Executed %s", " ".join(cmd))

        if not self._adb_ready:
            self._check_and_update_adbkey()
            self._adb_ready = True

        env_args = tuple(f"{k}={v}" for k, v in (extra_env or {}).items())
        # Replace ()"exec-out", "su", "-c",) for ("shell", ) for nonroot devices
        return super().create_process(
            "adb",
            "-s",
            testbed_defaults.serial_id,
            "exec-out",
            "su",
            "-c",
            *env_args,
            *cmd,
            logfile=logfile,
        )

    def run_binary(self, *args, **kwargs) -> Iterator[str]:
        for line in super().run_binary(*args, **kwargs):
            logging.debug(line)
            yield line


class SshExecutor(LocalExecutor):
    """
    SSH Executor
    """

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self._ssh_obj: Optional[paramiko.SSHClient] = None

    @property
    def _ssh(self) -> paramiko.SSHClient:
        """
        Create an SSH client
        """
        if self._ssh_obj is None:
            logging.getLogger("paramiko.transport").setLevel(logging.WARNING)
            ssh = paramiko.SSHClient()
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            ssh.connect(
                testbed_defaults.api_address,
                username=testbed_defaults.user,
                password=testbed_defaults.password,
                look_for_keys=False,
            )
            self._ssh_obj = ssh
        return self._ssh_obj

    def __del__(self):
        if self._ssh_obj is not None and self._ssh_obj.get_transport() is not None:
            self._ssh_obj.close()

    @contextmanager
    def _sftp(self) -> Generator[paramiko.SFTPClient, None, None]:
        sftp = self._ssh.open_sftp()
        try:
            yield sftp
        finally:
            sftp.close()

    def copy_file(
        self,
        path: Union[str, Path],
        destiny: Union[str, Path],
        is_remote_file: bool = False,
    ) -> None:
        if not is_remote_file:
            logging.info("Copying to remote: %s -> %s", path, destiny)
            with self._sftp() as sftp:
                sftp.put(str(path), str(destiny))
                sftp.chmod(str(destiny), 0o755)
        else:
            Path(destiny).parent.resolve().mkdir(parents=True, exist_ok=True)

            logging.info("Copying from remote: %s <- %s", path, destiny)
            with self._sftp() as sftp:
                sftp.get(str(path), str(destiny))

    def mkdir(self, path: Union[str, Path]) -> None:
        super().mkdir(path)
        path = Path(path)
        with self._sftp() as sftp:
            for partial in reversed([path, *path.parents]):
                with suppress(IOError):
                    sftp.mkdir(str(partial))

    def write_file(self, path: Union[str, Path], content: str) -> None:
        super().write_file(path, content)
        self.copy_file(path, path)

    def close_folder(self, path: Union[str, Path]) -> None:
        logging.info("Downloading from remote: %s <- %s", path, path)
        with self._sftp() as sftp:
            _download_sftp_dir(sftp, Path(path), Path(path))

    def find_in_path(self, binary_name: str) -> str:
        # First search it in path
        prefix_array: Tuple[str, ...] = ("",)
        if testbed_defaults.tma_path:
            prefix_array = (testbed_defaults.tma_path + "/", *prefix_array)
        for prefix in prefix_array:
            _, stdout, _ = self._ssh.exec_command(f'bash -l -c "which {prefix}{binary_name}"', get_pty=True)
            if stdout.channel.recv_exit_status() == 0:
                return stdout.read().decode().strip()
        raise FileNotFoundError(f"Can not found '{binary_name}' in path")

    def create_process(
        self, *cmd: str, logfile: Optional[TextIO] = None, extra_env: Optional[dict] = None
    ) -> SutProcessLike:
        binary_name, *binary_params = cmd
        env_prefix = " ".join(f"{k}={v}" for k, v in (extra_env or {}).items())
        return _RemoteProcess(
            self._ssh, self.find_in_path(binary_name), *binary_params, logfile=logfile, env_prefix=env_prefix
        )


def _download_sftp_dir(sftp: paramiko.SFTPClient, remote_dir: Path, local_dir: Path):
    """
    Recursively download a full directory
    """

    local_dir.mkdir(parents=True, exist_ok=True)
    for entry in sftp.listdir_attr(str(remote_dir)):
        remote_path = remote_dir.joinpath(entry.filename)
        local_path = local_dir.joinpath(entry.filename)

        if _remote_isdir(entry.st_mode):
            _download_sftp_dir(sftp, remote_path, local_path)
        else:
            try:
                sftp.get(str(remote_path), str(local_path))
            except FileNotFoundError:
                logging.warning("File not found: %s", remote_path)


def _remote_isdir(mode):
    """
    Check if the mode is a directory
    """
    return mode & 0o170000 == 0o040000


# pylint: disable=too-many-instance-attributes
class _RemoteProcess:
    def __init__(
        self,
        ssh: paramiko.SSHClient,
        *cmd: str,
        logfile: Optional[TextIO],
        env_prefix: str = "",
    ):

        self._ssh = ssh
        cmd_str = " ".join(cmd)
        if env_prefix:
            cmd_str = f"{env_prefix} {cmd_str}"
        self.stdin, self.stdout, self.stderr = self._ssh.exec_command(cmd_str)
        self._logfile = logfile

        self.pid: int = 0
        self._name = cmd[0].split("/")[-1]
        self.returncode: Optional[int] = None

        # Found pid
        _, stdout, _ = self._ssh.exec_command(f"pgrep -f {self._name}")
        with suppress(ValueError):
            self.pid = int(stdout.read().decode().strip())

        Thread(target=self._copy_stdout_to_logfile).start()

    def _copy_stdout_to_logfile(self):
        if self._logfile is not None:
            while True:
                for stream in (self.stdout, self.stderr):
                    while True:
                        line = stream.readline()
                        if not line:
                            break
                        self._logfile.write(line)
                        self._logfile.flush()
                if self.stdout.channel.exit_status_ready():
                    break
                sleep(0.1)

    def children(self, recursive=False):  # pylint: disable=unused-argument
        """
        Return the children of this process as a list of Process
        instances, pre-emptively checking whether PID has been reused.
        If *recursive* is True return all the parent descendants.
        """
        return []

    def name(self):
        """
        The process name. The return value is cached after first call.
        """
        return self._name

    def is_running(self):
        """
        Return whether this process is running.
        """
        return not self.stdout.channel.exit_status_ready()

    def wait(self, timeout=None):
        """
        Wait for process to terminate and, if process is a children
        of os.getpid(), also return its exit code, else None.

        If the process is already terminated immediately return None
        instead of raising NoSuchProcess.

        If *timeout* (in seconds) is specified and process is still
        alive raise TimeoutExpired.
        """

        if self.returncode is not None:
            return self.returncode

        start_time = time()
        while self.is_running():
            if timeout and (time() - start_time) >= timeout:
                raise psutil.TimeoutExpired(timeout or 0)
            sleep(0.1)

        self.returncode = self.stdout.channel.recv_exit_status()
        return self.returncode

    def send_signal(self, sig):
        """
        Send a signal *sig* to process pre-emptively checking
        whether PID has been reused (see signal module constants) .
        """
        if self.pid:
            _, stdout, _ = self._ssh.exec_command(f"kill -{sig} {self.pid}")
            if stdout.channel.recv_exit_status() != 0:
                raise psutil.NoSuchProcess(self.pid, self._name)

    def kill(self):
        """
        Kill the current process with SIGKILL pre-emptively checking
        whether PID has been reused.
        """
        self.send_signal(signal.SIGKILL)
