# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-cleanup-${organization_name}
  namespace: ${namespace}
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        metadata:
          annotations:
            retinaRunnerJob: "true"
        spec:
          serviceAccountName: retina-cronjobs-sa-${organization_name}
          containers:
            - name: cluster-cleanup-script
              image: ${image_repository}:${image_tag}
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh"]
              args:
                - "-c"
                - |
                  set -euo pipefail
                  /bin/sh /usr/local/bin/deletePods.sh ${taint_key}=${taint_value}
          imagePullSecrets:
            - name: registry-credentials
          tolerations:
            - key: ${taint_key}
              operator: "Equal"
              value: ${taint_value}
              effect: "NoSchedule"
          restartPolicy: Never
