# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${name}-${suffix}
  namespace: ${namespace}
spec:
  schedule: "${schedule}"
  timeZone: "${timezone}"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 50
      template:
        metadata:
          annotations:
            retinaRunnerJob: "true"
        spec:
          serviceAccountName: retina-cronjobs-sa-${suffix}
          volumes:
            - name: scripts
              configMap:
                name: ${scripts_configmap}
                defaultMode: 0o755
          containers:
            - name: runner-manager-script
              image: ${retina_registry_uri}/launcher:${retina_version}
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh"]
              args:
                - "-c"
                - |
                  set -euo pipefail
                  pip3 install "python-gitlab<9"
                  python3 /usr/local/bin/retina_runner.py --incluster ${join(" ", extra_args)}
              env:
                - name: RETINA_RUNNERS_CONFIGMAP
                  value: retina-runners-${suffix}
                - name: GITLAB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: gitlabtoken-${suffix}
                      key: GITLAB_TOKEN
              volumeMounts:
                - name: scripts
                  mountPath: /usr/local/bin/retina_runner.py
                  subPath: retina_runner.py
          imagePullSecrets:
            - name: registry-credentials
          tolerations: ${jsonencode(tolerations)}
          restartPolicy: Never
