# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/docker.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/version_check.yml
  - local: infrastructure/retina-cronjobs/version.yml

.docker-builder-retina-cronjobs:
  extends: .docker-builder
  variables:
    REGISTRY_URI: ${RETINA_REGISTRY_URI}
    NAME: cronjobs
    CONTEXT: infrastructure/retina-cronjobs/image
    VERSION: ${RETINA_CRONJOBS_VERSION}
    BUILD_ARGS: RETINA_VERSION=${RETINA_VERSION};RETINA_REGISTRY_URI=${RETINA_REGISTRY_URI}

cronjob container version changed:
  stage: static
  extends: .version increased
  rules:
    - if: $ON_MR
      changes: &retina_cronjobs_changes
        paths:
          - infrastructure/retina-cronjobs/image/Dockerfile
          - infrastructure/retina-cronjobs/image/**/*.py
          - infrastructure/retina-cronjobs/image/**/*.sh
  variables:
    FILE_PATH: infrastructure/retina-cronjobs/version.yml
    VARIABLE_NAME: RETINA_CRONJOBS_VERSION

only build base:
  stage: ci
  extends: .docker-builder-retina-cronjobs
  rules:
    - if: $ON_MR
      changes:
        <<: *retina_cronjobs_changes
  variables:
    MODE: test

build and publish final:
  stage: ci
  extends: .docker-builder-retina-cronjobs
  rules:
    - if: $ON_MR
      changes:
        <<: *retina_cronjobs_changes
      when: manual
      allow_failure: true
    - if: $ON_DEFAULT_BRANCH
      changes:
        <<: *retina_cronjobs_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  retry: 2
  variables:
    MODE: publish
