#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/docker.yml

stages:
  - test
  - publish

variables:
  OPEN5GS_VERSION: "2.7.0"

.docker-builder-open5gs:
  extends: .docker-builder
  variables: &image_variables
    NAME: retina/open5gs
    CONTEXT: retina/images/open5gs
    VERSION: ${OPEN5GS_VERSION}_${RETINA_VERSION}
    BUILD_ARGS: OPEN5GS_VERSION=v${OPEN5GS_VERSION};RETINA_VERSION=${RETINA_VERSION};CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "10G"

only-build:
  stage: test
  extends: .docker-builder-open5gs
  rules:
    - if: $ON_MR
  variables:
    MODE: test

build-and-publish:
  stage: publish
  extends: .docker-builder-open5gs
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  retry: 2
  variables:
    MODE: publish
    MULTI_ARCH_BUILD: "true"
  parallel:
    matrix:
      - PLATFORM: ["arm64", "amd64"]

publish manifest:
  stage: publish
  extends: .docker manifest
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    <<: *image_variables
  needs:
    - build-and-publish
