#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/python.yml
  - local: e2e/functional-config.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/static.yml

# E2E CI/CD Pipeline

## MR
e2e tests tox:
  extends: .tox
  stage: static
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/scripts/**/*
        - e2e/conftest.py
        - e2e/pyproject.toml
  variables:
    PY_DIR: e2e
  before_script:
    - apk add build-base

e2e dynamic tests validation:
  stage: static
  image:
    name: ${RETINA_REGISTRY_URI}/launcher:latest
    entrypoint: ["/bin/sh", "-c"]
  rules:
    - if: $ON_MR_FORK
      when: never
    - if: $ON_MR
      changes:
        - retina/launcher/**/*
        - e2e/tests/**/*
        - e2e/conftest.py
        - e2e/pyproject.toml
  script:
    - |
      cd ${CI_PROJECT_DIR}/e2e
      retina-launcher --collect-only
  needs:
    - job: launcher
      artifacts: false
      optional: true

e2e request validation:
  stage: static
  image:
    name: ${RETINA_REGISTRY_URI}/launcher:latest
    entrypoint: ["/bin/sh", "-c"]
  rules:
    - if: $ON_MR_FORK
      when: never
    - if: $ON_MR
      changes:
        - retina/orchestrator/**/*
        - e2e/retina_requests/**/*
  script:
    - |
      cd ${CI_PROJECT_DIR}/e2e/retina_requests
      python3 ${CI_PROJECT_DIR}/retina/_scripts/generate_env.py
      file_list=$(ls *.yml)
      for f in $file_list; do
          retina-request-checker --input $f
      done
  needs:
    - job: launcher
      artifacts: false
      optional: true

dynamically generated pipeline validation:
  extends: .static
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/suites/**/*
        - e2e/scripts/generate_pipelines.py
        - e2e/*.yml
        - .gitlab-ci-stages.yml
  script:
    - |
      python3 e2e/scripts/generate_pipelines.py --input_path=e2e/tests/suites --pipelines_output_path=e2e --stages_output_path=.
      is-pristine-repo.sh

## Build jobs for Scheduled Pipelines
zmq driver:
  extends: build trx driver
  retry: 2
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Watchdog/
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/

release with deb info:
  extends: build
  retry: 2
  cache: []
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Watchdog/
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /RF Nightly/
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    OS: ubuntu-24.04
    OCUDU_TARGET: ocu odu gnb
    COMPILER: gcc
    BUILD_ARGS: >
      -DENABLE_WERROR=False -DCMAKE_BUILD_TYPE=RelWithDebInfo -DMARCH=x86-64-v3
      -DASSERT_LEVEL=PARANOID
    TEST_MODE: none

debug:
  extends: build
  retry: 2
  cache: []
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
  variables:
    OS: ubuntu-24.04
    OCUDU_TARGET: gnb
    COMPILER: gcc
    BUILD_ARGS: >
      -DENABLE_WERROR=False -DCMAKE_BUILD_TYPE=Debug -DMARCH=x86-64-v3
      -DASSERT_LEVEL=PARANOID -DEXIT_TIMEOUT=120
    TEST_MODE: none

asan:
  extends: build
  retry: 2
  cache: []
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /RF Nightly/
  variables:
    OS: ubuntu-24.04
    OCUDU_TARGET: gnb
    COMPILER: clang
    BUILD_ARGS: >
      -DENABLE_WERROR=False -DCMAKE_BUILD_TYPE=Debug -DMARCH=x86-64-v3
      -DENABLE_ASAN=True -DASSERT_LEVEL=PARANOID -DEXIT_TIMEOUT=120
    TEST_MODE: none

tsan:
  extends: build
  retry: 2
  cache: []
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
  variables:
    OS: ubuntu-24.04
    OCUDU_TARGET: gnb
    COMPILER: clang
    BUILD_ARGS: >
      -DENABLE_WERROR=False -DCMAKE_BUILD_TYPE=Debug -DMARCH=x86-64-v3
      -DENABLE_TSAN=True -DASSERT_LEVEL=PARANOID -DEXIT_TIMEOUT=120
    TEST_MODE: none

dpdk rtsan avx512:
  extends: build
  retry: 2
  cache: []
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Weekly/
  variables:
    OS: ubuntu-24.04-rtsan
    OCUDU_TARGET: gnb_split_7_2 gnb
    COMPILER: clang
    DPDK_VERSION: 24.11.2_avx512
    BUILD_ARGS: >
      -DENABLE_WERROR=False -DCMAKE_BUILD_TYPE=Release -DFORCE_DEBUG_INFO=True -DMARCH=x86-64-v4
      -DENABLE_RTSAN=True -DENABLE_ZEROMQ=False -DENABLE_UHD=False -DENABLE_DPDK=True
      -DASSERT_LEVEL=AUTO -DEXIT_TIMEOUT=30
    TEST_MODE: none

## Emulated Nightly
### Test mode
.test mode ue:
  extends: e2e
  stage: test mode
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
  variables:
    GROUP: zmq
    TESTBED: test_mode_ue
    MARKERS: test_mode
    KEYWORDS: test_ue
    RETINA_ARGS: ue.all.log_level=warning gnb.all.log_level=warning 5gc.all.log_level=warning
    LAUNCHER_ARGS: -n 2

test ue:
  extends: .test mode ue
  needs:
    - release with deb info

test ue asan:
  extends: .test mode ue
  needs:
    - asan

.test mode ru:
  extends: e2e
  stage: test mode
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
  variables:
    GROUP: viavi
    TESTBED: test_mode_ru
    RETINA_ARGS: ue.all.log_level=warning gnb.all.log_level=warning 5gc.all.log_level=warning

ru dummy:
  extends: .test mode ru
  variables:
    MARKERS: test_mode
    KEYWORDS: test_ru
  needs:
    - dpdk rtsan avx512

ru dummy asan:
  extends: .test mode ru
  variables:
    MARKERS: test_mode_not_crash
    KEYWORDS: "test_ru"
  needs:
    - asan

ru dummy tsan:
  extends: .test mode ru
  variables:
    MARKERS: test_mode_not_crash
    KEYWORDS: "test_ru"
  needs:
    - tsan

ru dummy test many ues:
  extends: .test mode ru
  variables:
    MARKERS: test_mode_many_ues
    KEYWORDS: test_mode_many_ues
  needs:
    - dpdk rtsan avx512

### SRSUE
.srsue:
  extends: e2e
  stage: srsue
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
  variables:
    GROUP: zmq
    RETINA_ARGS: ue.all.log_level=info gnb.all.log_level=info 5gc.all.log_level=info
    LAUNCHER_ARGS: -n 2
  needs:
    - release with deb info

srsue basic:
  extends: .srsue
  variables:
    TESTBED: zmq_srsue
    MARKERS: zmq_srsue

ric:
  extends: .srsue
  variables:
    TESTBED: zmq_ric
    MARKERS: zmq_ric

### Amarisoft ZMQ
.amarisoft_zmq:
  extends: e2e
  stage: amarisoft zmq
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
  variables:
    GROUP: zmq
    TESTBED: zmq
    LAUNCHER_ARGS: -n 2
    RETINA_ARGS: >
      gnb.all.pcap=True gnb.all.mac_enable=True gnb.all.enable_integrity_protection=True
      ue.all.log_level=info gnb.all.log_level=info 5gc.all.log_level=info
  needs:
    - zmq driver
    - release with deb info

smoke zmq:
  extends: .amarisoft_zmq
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Watchdog/
  variables:
    MARKERS: smoke
    LAUNCHER_ARGS: -x
    RETINA_ARGS: >
      ue.all.pdcch_decode_opt_threshold=0.1
      gnb.all.pcap=True gnb.all.mac_enable=True gnb.all.enable_integrity_protection=True
      ue.all.log_level=info gnb.all.log_level=info 5gc.all.log_level=info

gnb 1UE:
  extends: .amarisoft_zmq
  variables:
    MARKERS: zmq_single_ue

gnb 1UE ntn:
  extends: .amarisoft_zmq
  rules:
    - if: $NTN_CHANNEL_EMULATOR_PACKAGE_REGISTRY && $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
  variables:
    TESTBED: zmq_ntn
    MARKERS: zmq_ntn
    LAUNCHER_ARGS: ""
  parallel:
    matrix:
      - E2E_FILE_OR_DIR: tests/ping.py
      - E2E_FILE_OR_DIR: tests/iperf.py

gnb 4UE:
  extends: .amarisoft_zmq
  variables:
    FILE_OR_DIR: tests/slicing.py

gnb 4UE asan:
  extends: .amarisoft_zmq
  variables:
    MARKERS: smoke
    KEYWORDS: iperf
  needs:
    - zmq driver
    - asan

gnb 4UE tsan:
  extends: .amarisoft_zmq
  variables:
    MARKERS: smoke
    KEYWORDS: iperf
  needs:
    - zmq driver
    - tsan

gnb 4UE memcheck:
  extends: .amarisoft_zmq
  variables:
    MARKERS: zmq_valgrind
    RETINA_ARGS: >
      gnb.all.pcap=True gnb.all.mac_enable=True gnb.all.rlc_enable=True gnb.all.enable_integrity_protection=True
      ue.all.log_level=info gnb.all.log_level=warning 5gc.all.log_level=info
  needs:
    - zmq driver
    - debug

gnb 8UE:
  extends: .amarisoft_zmq
  variables:
    MARKERS: zmq and not smoke
  timeout: 4h
  parallel:
    matrix:
      - FILE_OR_DIR: tests/attach_detach.py
      - FILE_OR_DIR: tests/reestablishment.py
        KEYWORDS: sequentially
      - FILE_OR_DIR: tests/reestablishment.py
        KEYWORDS: "not sequentially"
      - FILE_OR_DIR: tests/handover.py
        KEYWORDS: sequentially

gnb 32UE:
  extends: .amarisoft_zmq
  variables:
    MARKERS: "zmq and not smoke"
  parallel:
    matrix:
      - FILE_OR_DIR: tests/iperf.py
        KEYWORDS:
          [
            "udp and band:3",
            "udp and not band:3",
            "tcp and band:3",
            "tcp and not band:3 and not precoding",
            "tcp and not band:3 and precoding",
          ]
      - FILE_OR_DIR: tests/ping.py
        KEYWORDS: "32"
      - FILE_OR_DIR: tests/handover.py
        KEYWORDS: "not sequentially"
      - MARKERS: zmq_2x2_mimo

gnb 32UE [tests/pucch.py]:
  extends: .amarisoft_zmq
  variables:
    MARKERS: "zmq and not smoke"
    FILE_OR_DIR: tests/pucch.py
    RETINA_ARGS: >
      ue.all.pdcch_decode_opt_threshold=0.1
      gnb.all.pcap=True gnb.all.mac_enable=True gnb.all.enable_integrity_protection=True
      ue.all.log_level=info gnb.all.log_level=info 5gc.all.log_level=info

gnb 64UE:
  extends: .amarisoft_zmq
  variables:
    FILE_OR_DIR: tests/iperf.py
    KEYWORDS: "64"

cudu 8UE:
  extends: .amarisoft_zmq
  timeout: 2h
  variables:
    TESTBED: zmq_cudu
    MARKERS: "zmq and not smoke"
    FILE_OR_DIR: tests/reestablishment.py
    KEYWORDS: sequentially

cudu 32UE:
  extends: .amarisoft_zmq
  timeout: 2h
  variables:
    TESTBED: zmq_cudu
    FILE_OR_DIR: tests/iperf.py
    KEYWORDS: "tcp and not band:3 and bandwidth:50 and not precoding"
    MARKERS: "zmq and not smoke"

cudu 64UE:
  extends: .amarisoft_zmq
  timeout: 3h
  variables:
    TESTBED: zmq_cudu
    FILE_OR_DIR: tests/ping.py
    KEYWORDS: "64"
    MARKERS: "zmq and not smoke"

1cu2du 8UE:
  extends: .amarisoft_zmq
  timeout: 2h
  variables:
    TESTBED: zmq_1cu2du
    MARKERS: "zmq and not smoke"
    FILE_OR_DIR: tests/inter_du_handover.py
    KEYWORDS: sequentially

2gnb:
  extends: .amarisoft_zmq
  timeout: 2h
  variables:
    TESTBED: zmq_2gnb
    MARKERS: "zmq and not smoke"
    FILE_OR_DIR: tests/inter_cu_handover.py

### Amarisoft s72
.amarisoft s72:
  extends: e2e
  stage: amarisoft s72
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
  variables:
    GROUP: viavi
    TESTBED: s72
    MARKERS: s72
    RETINA_ARGS: >
      gnb.all.pcap=True gnb.all.rlc_enable=False gnb.all.enable_integrity_protection=True
      ue.all.log_level=warning gnb.all.log_level=warning 5gc.all.log_level=warning
  needs:
    - dpdk rtsan avx512

gnb 1UE s72:
  extends: .amarisoft s72
  variables:
    KEYWORDS: not handover and not fr2

gnb 2UE s72:
  extends: .amarisoft s72
  variables:
    KEYWORDS: handover

gnb 1UE s72 FR2:
  extends: .amarisoft s72
  variables:
    TESTBED: s72_fr2
    KEYWORDS: s72_fr2

### Viavi
.viavi:
  extends: e2e
  stage: viavi
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Nightly/
  timeout: 8h
  variables:
    GROUP: viavi
    TESTBED: viavi
    MARKERS: viavi
    RETINA_ARGS: >
      gnb.all.pcap=True gnb.all.rlc_enable=True gnb.all.rlc_rb_type=srb
      ue.all.log_level=warning gnb.all.log_level=warning 5gc.all.log_level=warning
  needs:
    - dpdk rtsan avx512

1UE:
  extends: .viavi
  variables:
    KEYWORDS: "1UE and ideal and not MIMO"

1UE MIMO:
  extends: .viavi
  variables:
    KEYWORDS: "1UE and ideal and MIMO"

1UE birth-death:
  extends: .viavi
  variables:
    KEYWORDS: "1UE and birth-death"

1UE fading:
  extends: .viavi
  variables:
    KEYWORDS: "1UE and fading and not MIMO"

1UE fading MIMO:
  extends: .viavi
  variables:
    KEYWORDS: "1UE and fading and MIMO"

32UE ping:
  extends: .viavi
  variables:
    KEYWORDS: "32UE and ping"

32UE UDP:
  extends: .viavi
  variables:
    KEYWORDS: "32UE and ideal and not long and not tdd and not UM and udp"

32UE TCP:
  extends: .viavi
  variables:
    KEYWORDS: "32UE and ideal and not long and not tdd and not UM and tcp"

32UE fading:
  extends: .viavi
  variables:
    KEYWORDS: "32UE and fading"

32UE tdd:
  extends: .viavi
  variables:
    KEYWORDS: "32UE and tdd"

## RF Nightly
### SDR
.amarisoft sdr:
  extends: e2e
  stage: amarisoft sdr
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /RF Nightly/
  variables:
    GROUP: rf
    TESTBED: rf_b200
    RETINA_ARGS: >
      ue.all.log_level=warning gnb.all.log_level=warning 5gc.all.log_level=warning
  needs:
    - release with deb info

b200 asan:
  extends: .amarisoft sdr
  variables:
    MARKERS: rf_not_crash
  needs:
    - asan

validate b200 config:
  extends: .amarisoft sdr
  variables:
    MARKERS: rf_b200

### Android
.android:
  extends: e2e
  stage: android
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /RF Nightly/
  variables:
    GROUP: rf
    MARKERS: android
    RETINA_ARGS: >
      ue.all.log_level=warning gnb.all.log_level=warning 5gc.all.log_level=warning
  needs:
    - release with deb info

xiaomi b200:
  extends: .android
  variables:
    TESTBED: android_b200
    KEYWORDS: "not ims"

xiaomi b200 drx:
  extends: .android
  variables:
    TESTBED: android_b200
    MARKERS: android_drx

xiaomi x300:
  extends: .android
  variables:
    TESTBED: android_x300
    MARKERS: android_hp

xiaomi x300 ims:
  extends: .android
  variables:
    TESTBED: android_callbox
    MARKERS: android
    KEYWORDS: ims

## Emulated Weekly
### Viavi
.viavi_weekly:
  extends: .viavi
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /Emulated Weekly/

32UE um:
  extends: .viavi_weekly
  variables:
    KEYWORDS: "ideal and UM"

32UE 3h:
  extends: .viavi_weekly
  variables:
    KEYWORDS: 3h

32UE 24h:
  extends: .viavi_weekly
  timeout: 26 hours
  variables:
    KEYWORDS: 24h
