#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
inter_ru_ho:
  stage: mobility
  extends: .amarisoft_zmq
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/suites/**/*
        - e2e/scripts/generate_pipelines.py
        - e2e/*.yml
        - .gitlab-ci-stages.yml
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: functional::mobility::inter_ru_ho
    TESTBED: zmq_mme

ping:
  stage: multiue
  extends: .amarisoft_zmq
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/suites/**/*
        - e2e/scripts/generate_pipelines.py
        - e2e/*.yml
        - .gitlab-ci-stages.yml
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: functional::multiue::ping
    TESTBED: zmq_mme
