# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
inter_ru_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/mobility/inter_ru_ho::"
    TESTBED: dynamic

intra_ru_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/mobility/intra_ru_ho::"
    TESTBED: dynamic

reestablishment:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/mobility/reestablishment::"
    TESTBED: dynamic

attach_dettach:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/multiue/attach_dettach::"
    TESTBED: dynamic

mobility:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/multiue/mobility::"
    TESTBED: dynamic

ping:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/multiue/ping::"
    TESTBED: dynamic

udp_bi:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/multiue/udp_bi::"
    TESTBED: dynamic

cmas:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/singleue/cmas::"
    TESTBED: dynamic

fdd_siso:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/singleue/fdd_siso::"
    TESTBED: dynamic

gbr_vonr:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/singleue/gbr_vonr::"
    TESTBED: dynamic

phy_configs:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/singleue/phy_configs::"
    TESTBED: dynamic

power_control:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/singleue/power_control::"
    TESTBED: dynamic

slicing:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/singleue/slicing::"
    TESTBED: dynamic

tdd_mimo:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/singleue/tdd_mimo::"
    TESTBED: dynamic

tdd_siso:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $ON_MR
      changes:
        - e2e/tests/**/*
        - e2e/*.yml
        - retina/**/*
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
  variables:
    KEYWORDS: "functional/singleue/tdd_siso::"
    TESTBED: dynamic
