# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: gitlab-glr-priority
value: 500000
globalDefault: true
description: "This priority class should be used for retina service pods only!"
