# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: retina-rolebinding
  namespace: retina
subjects:
  - kind: User
    name: retina
roleRef:
  kind: Role
  name: retina-role
  apiGroup: rbac.authorization.k8s.io
