# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/docker.yml

stages:
  - test
  - publish

.docker-builder-ocudu-base:
  extends: .docker-builder
  variables:
    REGISTRY_URI: ${RETINA_REGISTRY_URI}
    NAME: ocudu-base
    VERSION: ${RETINA_VERSION}
    CONTEXT: retina/images/ocudu/base
    BUILDER_IMAGE_NAME: builder-ubuntu-${AGENT_OS_VERSION}:${DOCKER_BUILDER_VERSION}
    BUILD_ARGS: RETINA_VERSION=${RETINA_VERSION};RETINA_REGISTRY_URI=${RETINA_REGISTRY_URI};BUILDER_IMAGE=${OCUDU_REGISTRY_URI}/${BUILDER_IMAGE_NAME}
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "100G"
    KUBERNETES_EPHEMERAL_STORAGE_LIMIT: "100G"
  tags: [saas-linux-large-amd64]

only build base:
  stage: test
  extends: .docker-builder-ocudu-base
  rules:
    - if: $ON_MR
  variables:
    MODE: test

build and publish base:
  stage: publish
  extends: .docker-builder-ocudu-base
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  retry: 2
  variables:
    MODE: publish

build and publish final:
  stage: publish
  extends: .docker-builder
  variables:
    REGISTRY_URI: ${RETINA_REGISTRY_URI}
    VERSION: ${RETINA_VERSION}
    CONTEXT: retina/images/ocudu
    BUILD_ARGS: RETINA_VERSION=${RETINA_VERSION};RETINA_REGISTRY_URI=${RETINA_REGISTRY_URI};RETINA_AGENT=${RETINA_AGENT}
    MODE: publish
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "80G"
    KUBERNETES_EPHEMERAL_STORAGE_LIMIT: "80G"
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  retry: 2
  parallel:
    matrix:
      - NAME: ocudu-gnb
        RETINA_AGENT: ocudu-gnb
      - NAME: ocudu-cudu
        RETINA_AGENT: ocudu-cudu
      - NAME: ocudu-cu
        RETINA_AGENT: ocudu-cu
      - NAME: ocudu-du
        RETINA_AGENT: ocudu-du
  needs:
    - build and publish base
