#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/version_check.yml
  - local: retina/version.yml

.path_changes:
  - &version_changes retina/version.yml
  - &protocol_changes retina/protocol/**/*
  - &client_changes retina/client/**/*
  - &viavi_changes retina/viavi/**/*
  - &agent_changes retina/agent/**/*
  - changes: &agent_container_changes
      paths:
        - retina/agent/**/Dockerfile
        - retina/agent/**/*.sh
  - &images_changes retina/images/**/*
  - &amarisoftue_changes retina/images/amarisoftue/**/*
  - &amarisoftue_remote_changes retina/images/amarisoftue_remote/**/*
  - &amarisoft5gc_remote_changes retina/images/amarisoft5gc_remote/**/*
  - &android_changes retina/images/android/**/*
  - &open5gs_changes retina/images/open5gs/**/*
  - &ocudu_changes retina/images/ocudu/**/*
  - &ocudu_remote_changes retina/images/ocudu_remote/**/*
  - &srsue_changes retina/images/srsue/**/*
  - &flexric_changes retina/images/flexric/**/*
  - &ntn_channel_emulator_changes retina/images/ntn-channel-emulator/**/*
  - &orchestrator_changes retina/orchestrator/**/*
  - &launcher_changes retina/launcher/**/*

warning:
  stage: static
  rules:
    - if: $SKIP_RETINA_CI && $ON_MR
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *client_changes
          - *viavi_changes
          - *agent_changes
          - *images_changes
          - *orchestrator_changes
          - *launcher_changes
  image: alpine:3
  allow_failure: true
  script:
    - |
      echo "WARNING: Retina code has been modified but CI/CD is skipped for this pipeline as SKIP_RETINA_CI is set."
      exit 1
  needs: []

version changed:
  stage: static
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        paths:
          - *version_changes
          - *viavi_changes
          - *protocol_changes
          - *client_changes
          - *agent_changes
          - *orchestrator_changes
          - *launcher_changes
  extends: .version increased
  variables:
    FILE_PATH: retina/version.yml
    VARIABLE_NAME: RETINA_VERSION

################################################################################
## Launch Downstream
################################################################################
viavi-client:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        paths:
          - *viavi_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *viavi_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/viavi/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  needs: []

protocol:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        paths:
          - *protocol_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/protocol/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  needs: []

client:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        paths:
          - *protocol_changes
          - *client_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *client_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/client/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  needs:
    - job: protocol
      optional: true
      artifacts: false

agent:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        paths:
          - *protocol_changes
          - *agent_changes
          - *images_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *agent_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/agent/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  needs:
    - job: protocol
      optional: true
      artifacts: false

amarisoftue image:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        <<: *agent_container_changes
    - if: $ON_MR
      changes:
        paths:
          - *amarisoftue_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *agent_changes
          - *amarisoftue_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/images/amarisoftue/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  variables: &images_variables
    AGENT_OS_VERSION: "24.04"
  needs:
    - job: protocol
      optional: true
      artifacts: false
    - job: agent
      optional: true
      artifacts: false

amarisoftue remote image:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        <<: *agent_container_changes
    - if: $ON_MR
      changes:
        paths:
          - *amarisoftue_remote_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *agent_changes
          - *amarisoftue_remote_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/images/amarisoftue_remote/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  variables:
    <<: *images_variables
  needs:
    - job: protocol
      optional: true
      artifacts: false
    - job: agent
      optional: true
      artifacts: false

amarisoft5gc remote image:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        <<: *agent_container_changes
    - if: $ON_MR
      changes:
        paths:
          - *amarisoft5gc_remote_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *agent_changes
          - *amarisoft5gc_remote_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/images/amarisoft5gc_remote/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  variables:
    <<: *images_variables
  needs:
    - job: protocol
      optional: true
      artifacts: false
    - job: agent
      optional: true
      artifacts: false

android image:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        <<: *agent_container_changes
    - if: $ON_MR
      changes:
        paths:
          - *android_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *agent_changes
          - *android_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/images/android/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  variables:
    <<: *images_variables
  needs:
    - job: protocol
      optional: true
      artifacts: false
    - job: agent
      optional: true
      artifacts: false

open5gs image:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        <<: *agent_container_changes
    - if: $ON_MR
      changes:
        paths:
          - *open5gs_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *agent_changes
          - *android_changes
          - *open5gs_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/images/open5gs/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  variables:
    <<: *images_variables
  needs:
    - job: protocol
      optional: true
      artifacts: false
    - job: agent
      optional: true
      artifacts: false

ocudu image:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        <<: *agent_container_changes
    - if: $ON_MR
      changes:
        paths:
          - *ocudu_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *agent_changes
          - *ocudu_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/images/ocudu/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  variables:
    <<: *images_variables
  needs:
    - job: protocol
      optional: true
      artifacts: false
    - job: agent
      optional: true
      artifacts: false

ocudu remote image:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        <<: *agent_container_changes
    - if: $ON_MR
      changes:
        paths:
          - *ocudu_remote_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *agent_changes
          - *ocudu_remote_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/images/ocudu_remote/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  variables:
    <<: *images_variables
  needs:
    - job: protocol
      optional: true
      artifacts: false
    - job: agent
      optional: true
      artifacts: false

srsue image:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        <<: *agent_container_changes
    - if: $ON_MR
      changes:
        paths:
          - *srsue_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *agent_changes
          - *srsue_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/images/srsue/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  variables:
    <<: *images_variables
  needs:
    - job: protocol
      optional: true
      artifacts: false
    - job: agent
      optional: true
      artifacts: false

flexric image:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        <<: *agent_container_changes
    - if: $ON_MR
      changes:
        paths:
          - *flexric_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *agent_changes
          - *flexric_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/images/flexric/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  variables:
    <<: *images_variables
  needs:
    - job: protocol
      optional: true
      artifacts: false
    - job: agent
      optional: true
      artifacts: false

ntn-channel-emulator image:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $NTN_CHANNEL_EMULATOR_PACKAGE_REGISTRY && $ON_MR
      changes:
        <<: *agent_container_changes
    - if: $NTN_CHANNEL_EMULATOR_PACKAGE_REGISTRY && $ON_MR
      changes:
        paths:
          - *ntn_channel_emulator_changes
    - if: $NTN_CHANNEL_EMULATOR_PACKAGE_REGISTRY && $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *agent_changes
          - *ntn_channel_emulator_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/images/ntn-channel-emulator/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  variables:
    <<: *images_variables
  needs:
    - job: protocol
      optional: true
      artifacts: false
    - job: agent
      optional: true
      artifacts: false

orchestrator:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        paths:
          - *protocol_changes
          - *orchestrator_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *version_changes
          - *protocol_changes
          - *orchestrator_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/orchestrator/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  needs:
    - job: protocol
      optional: true
      artifacts: false

launcher:
  stage: ci
  rules:
    - if: $SKIP_RETINA_CI
      when: never
    - if: $ON_MR
      changes:
        paths:
          - *viavi_changes
          - *protocol_changes
          - *client_changes
          - *orchestrator_changes
          - *launcher_changes
    - if: $ON_DEFAULT_BRANCH
      changes:
        paths:
          - *viavi_changes
          - *version_changes
          - *protocol_changes
          - *client_changes
          - *orchestrator_changes
          - *launcher_changes
        compare_to: "$CI_COMMIT_BEFORE_SHA"
  trigger:
    include:
      - local: retina/launcher/.gitlab-ci.yml
        inputs:
          ocudu_ref: $[[ inputs.ocudu_ref ]]
          ocudu_path: $[[ inputs.ocudu_path ]]
    strategy: depend
  needs:
    - job: protocol
      optional: true
      artifacts: false
    - job: client
      optional: true
      artifacts: false
    - job: orchestrator
      optional: true
      artifacts: false
