# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

inter_cu_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.inter_cu_ho."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

inter_du_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.inter_du_ho."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

inter_ru_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.inter_ru_ho."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

intra_ru_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.intra_ru_ho."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

paging:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.paging."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

reestablishment:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.reestablishment."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

cplane_traffic_load:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.cplane_traffic_load."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

mobility:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.mobility."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

qos:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.qos."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

simultaneous_udp:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.simultaneous_udp."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

slice:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.slice."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

test_mode:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.test_mode."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

traffic_model:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.traffic_model."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

ue_state_transition:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.ue_state_transition."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

bands:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.bands."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

bandwiths:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.bandwiths."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

configured_grant:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.configured_grant."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

drb_triggered_ul_grant:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.drb_triggered_ul_grant."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

emergency_call:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.emergency_call."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

fdd_siso:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.fdd_siso."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

gbr_vonr:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.gbr_vonr."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

mocn:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.mocn."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

nrppa:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.nrppa."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

ntn:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.ntn."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

phy_configs:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.phy_configs."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

power_control:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.power_control."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

pws:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.pws."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

rach:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.rach."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

security:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.security."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

slicing:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.slicing."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

tdd_mimo:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.tdd_mimo."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"

tdd_siso:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.tdd_siso."
    TESTBED: dynamic
    MARKERS: "zmq or test_mode_ue"
