# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

coverage:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.coverage."
    TESTBED: dynamic
    MARKERS: "zmq"

inter_cu_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.inter_cu_ho."
    TESTBED: dynamic
    MARKERS: "zmq"

inter_du_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.inter_du_ho."
    TESTBED: dynamic
    MARKERS: "zmq"

inter_ru_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.inter_ru_ho."
    TESTBED: dynamic
    MARKERS: "zmq"

intra_ru_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.intra_ru_ho."
    TESTBED: dynamic
    MARKERS: "zmq"

paging:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.paging."
    TESTBED: dynamic
    MARKERS: "zmq"

reestablishment:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.reestablishment."
    TESTBED: dynamic
    MARKERS: "zmq"

cplane_traffic_load:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.cplane_traffic_load."
    TESTBED: dynamic
    MARKERS: "zmq"

mobility:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.mobility."
    TESTBED: dynamic
    MARKERS: "zmq"

qos:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.qos."
    TESTBED: dynamic
    MARKERS: "zmq"

simultaneous_udp:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.simultaneous_udp."
    TESTBED: dynamic
    MARKERS: "zmq"

slice:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.slice."
    TESTBED: dynamic
    MARKERS: "zmq"

traffic_model:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.traffic_model."
    TESTBED: dynamic
    MARKERS: "zmq"

ue_state_transition:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.ue_state_transition."
    TESTBED: dynamic
    MARKERS: "zmq"

bands:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.bands."
    TESTBED: dynamic
    MARKERS: "zmq"

bandwiths:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.bandwiths."
    TESTBED: dynamic
    MARKERS: "zmq"

drb_triggered_ul_grant:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.drb_triggered_ul_grant."
    TESTBED: dynamic
    MARKERS: "zmq"

emergency_call:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.emergency_call."
    TESTBED: dynamic
    MARKERS: "zmq"

fdd_siso:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.fdd_siso."
    TESTBED: dynamic
    MARKERS: "zmq"

gbr_vonr:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.gbr_vonr."
    TESTBED: dynamic
    MARKERS: "zmq"

mocn:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.mocn."
    TESTBED: dynamic
    MARKERS: "zmq"

nrppa:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.nrppa."
    TESTBED: dynamic
    MARKERS: "zmq"

ntn:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.ntn."
    TESTBED: dynamic
    MARKERS: "zmq"

phy_configs:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.phy_configs."
    TESTBED: dynamic
    MARKERS: "zmq"

power_control:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.power_control."
    TESTBED: dynamic
    MARKERS: "zmq"

pws:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.pws."
    TESTBED: dynamic
    MARKERS: "zmq"

security:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.security."
    TESTBED: dynamic
    MARKERS: "zmq"

slicing:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.slicing."
    TESTBED: dynamic
    MARKERS: "zmq"

tdd_mimo:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.tdd_mimo."
    TESTBED: dynamic
    MARKERS: "zmq"

tdd_siso:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.tdd_siso."
    TESTBED: dynamic
    MARKERS: "zmq"
