# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

inter_cu_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.mobility.inter_cu_ho."
    TESTBED: dynamic

inter_du_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.mobility.inter_du_ho."
    TESTBED: dynamic

inter_ru_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.mobility.inter_ru_ho."
    TESTBED: dynamic

intra_ru_ho:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.mobility.intra_ru_ho."
    TESTBED: dynamic

paging:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.mobility.paging."
    TESTBED: dynamic

reestablishment:
  stage: mobility
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.mobility.reestablishment."
    TESTBED: dynamic

attach_detach:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.multiue.attach_detach."
    TESTBED: dynamic

load_test:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.multiue.load_test."
    TESTBED: dynamic

mobility:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.multiue.mobility."
    TESTBED: dynamic

ping:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.multiue.ping."
    TESTBED: dynamic

qos:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.multiue.qos."
    TESTBED: dynamic

slice:
  stage: multiue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.multiue.slice."
    TESTBED: dynamic

bands:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.bands."
    TESTBED: dynamic

bandwiths:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.bandwiths."
    TESTBED: dynamic

cmas:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.cmas."
    TESTBED: dynamic

drb_triggered_ul_grant:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.drb_triggered_ul_grant."
    TESTBED: dynamic

emergency_call:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.emergency_call."
    TESTBED: dynamic

fdd_siso:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.fdd_siso."
    TESTBED: dynamic

gbr_vonr:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.gbr_vonr."
    TESTBED: dynamic

mocn:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.mocn."
    TESTBED: dynamic

nrppa:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.nrppa."
    TESTBED: dynamic

ntn:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.ntn."
    TESTBED: dynamic

phy_configs:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.phy_configs."
    TESTBED: dynamic

power_control:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.power_control."
    TESTBED: dynamic

security:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.security."
    TESTBED: dynamic

slicing:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.slicing."
    TESTBED: dynamic

tdd_mimo:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.tdd_mimo."
    TESTBED: dynamic

tdd_siso:
  stage: singleue
  extends: .functional_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /functional/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "functional.singleue.tdd_siso."
    TESTBED: dynamic
