# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

coverage:
  stage: mobility
  extends: .performance_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^performance/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.coverage."
    TESTBED: dynamic
    MARKERS: "s72"

paging:
  stage: mobility
  extends: .performance_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^performance/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "mobility.paging."
    TESTBED: dynamic
    MARKERS: "s72"

capacity:
  stage: multiue
  extends: .performance_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^performance/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "multiue.capacity."
    TESTBED: dynamic
    MARKERS: "s72"

udp_dl:
  stage: singleue
  extends: .performance_e2e
  rules:
    - if: $CI_PIPELINE_SCHEDULE_DESCRIPTION =~ /^performance/
    - when: manual
      allow_failure: true
  variables:
    KEYWORDS: "singleue.udp_dl."
    TESTBED: dynamic
    MARKERS: "s72"
