# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

{{- range .Values.namespaces}}
apiVersion: v1
kind: Secret
metadata:
  name: {{$.Values.secretName}}
  namespace: {{.}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{$.Values.authToken | quote}}
---
{{- end}}
