# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/docker.yml
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/python.yml

stages:
  - static
  - publish

.launcher-docker:
  extends: .docker-builder
  variables: &image_variables
    PYTHON_VERSION: "3.12"
    OS: alpine
    REGISTRY_URI: ${RETINA_REGISTRY_URI}
    NAME: launcher
    CONTEXT: ${CI_PROJECT_DIR}/retina
    DOCKERFILE: retina/launcher
    BUILD_ARGS: PYTHON_VERSION=${PYTHON_VERSION};OS=${OS};RETINA_VERSION=${RETINA_VERSION}
    VERSION: ${RETINA_VERSION}

.launcher_build_dependencies:
  before_script:
    - |
      . /etc/os-release

      echo "Setting up the OS"
      case "$ID" in
        debian | ubuntu) DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends build-essential libffi-dev ;;
                 alpine) apk add build-base linux-headers libffi-dev ;;
                      *) echo 'Unsupported OS' && exit 1 ;;
      esac
  variables:
    PY_DIR: retina/launcher

tox:
  stage: static
  extends:
    - .launcher_build_dependencies
    - .tox

build docker:
  stage: static
  extends: .launcher-docker
  rules:
    - if: $ON_MR
  variables:
    MODE: build

publish deps:
  stage: publish
  extends:
    - .launcher_build_dependencies
    - .publish deps

publish wheel:
  stage: publish
  extends:
    - .launcher_build_dependencies
    - .publish wheel

publish docker:
  stage: publish
  extends: .launcher-docker
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    MODE: publish

publish latest:
  stage: publish
  extends: .docker manifest
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    <<: *image_variables
  needs:
    - publish docker
  script:
    - |
      docker manifest create \
        ${RETINA_REGISTRY_URI}/${NAME}:latest \
        --amend ${RETINA_REGISTRY_URI}/${NAME}:${VERSION}
      docker manifest push ${RETINA_REGISTRY_URI}/${NAME}:latest
      echo "Image ${RETINA_REGISTRY_URI}/${NAME}:latest pushed"
