# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

#########
# Build #
#########
[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61", "wheel"]

###########
# Project #
###########
[project]
authors = [
  {name = "Software Radio Systems"},
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Development Status :: 4 - Beta",
  "Framework :: Pytest",
]
dependencies = [
  "pytest < 9",
  "pytest-html < 5",
  "pytest-json < 1",
  "pytest-random-order < 2",
  "pytest-rerunfailures < 17",
  "pytest-xdist < 4",
  "jinja2 < 4",
  "PyYAML < 7",
  "rich < 14",
  "retina-client",
  "retina-orchestrator",
  "retina-viavi",
]
description = "Retina launcher"
dynamic = ["version"]
name = "retina_launcher"
requires-python = ">=3.9"

[project.scripts]
retina-launcher = "retina.launcher.__main__:main"

[project.entry-points.pytest11]
retina = "retina.launcher.plugin"

#############
# Dev Tools #
#############
[tool.black]
line-length = 120

[tool.isort]
atomic = true
combine_as_imports = true
float_to_top = true
force_alphabetical_sort_within_sections = true
include_trailing_comma = true
known_first_party = ["retina"]
line_length = 120
profile = "black"
remove_redundant_aliases = true

[tool.mypy]
check_untyped_defs = true
explicit_package_bases = true
install_types = true
mypy_path = [
  "src",
  "../client/src",
  "../orchestrator/src",
  "../protocol/src",
  "../viavi/src",
]
non_interactive = true
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
  "retina.protocol.base_pb2",
  "retina.protocol.base_pb2_grpc",
  "retina.protocol.ue_pb2",
  "retina.protocol.ue_pb2_grpc",
  "retina.protocol.gnb_pb2",
  "retina.protocol.gnb_pb2_grpc",
  "retina.protocol.fivegc_pb2",
  "retina.protocol.fivegc_pb2_grpc",
  "retina.protocol.ric_pb2",
  "retina.protocol.ric_pb2_grpc",
]
ignore_errors = true

[[tool.mypy.overrides]]
module = [
  "_pytest",
  "_pytest.mark",
  "_pytest.mark.structures",
  "click",
  "dotenv",
  "jinja2",
  "kubernetes",
  "kubernetes.client",
  "kubernetes.client.exceptions",
  "kubernetes.config",
  "kubernetes.config.config_exception",
  "kubernetes.config.incluster_config",
  "pytest",
  "pytest_html",
  "rich",
  "rich.console",
  "rich.table",
  "websockets",
  "websockets.asyncio.client",
  "websockets.exceptions",
]
ignore_missing_imports = true

[tool.pylint]
ignore-signatures = true
load-plugins = "pylint_pytest"
max-line-length = 120

[tool.pylint.typecheck]
ignored-modules = ["google.protobuf.*", "retina.protocol.*pb2*"]

[tool.coverage.run]
branch = true
source = ["src/retina/launcher"]

[tool.tox]
legacy_tox_ini = """
[tox]
minversion = 4.4.0
envlist = 
  format
  lint
  type
  build

[testenv]
passenv = RETINA_VERSION

[pkgenv]
passenv = RETINA_VERSION

[testenv:format]
skip_install = true
deps =
  black <= 26.3.1
  isort <= 8.0.1
commands =
  black src
  isort src

[testenv:lint]
deps =
  pylint <= 4.0.5
  pylint-pytest <= 1.1.8
  -e ../protocol
  -e ../client
  -e ../orchestrator
  -e ../viavi
commands =
  pylint src

[testenv:type]
skip_install = true
deps =
  mypy <= 1.20.0
commands =
  mypy src

[testenv:unittest]
usedevelop = True
deps =
  coverage[toml] <= 7.13.5
  -e ../protocol
  -e ../client
  -e ../orchestrator
  -e ../viavi
commands =
  coverage run -m unittest discover -v
  coverage report
  coverage xml
  coverage html

[testenv:build]
skip_install = true
deps =
  setuptools >= 61, <= 82.0.1
  wheel <= 0.46.3
  build <= 1.4.2
  -e ../protocol
  -e ../client
  -e ../orchestrator
  -e ../viavi
commands =
  python -m build --no-isolation
"""
