#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

services:
  docusaurus:
    image: node:20
    working_dir: /workdir/docs
    volumes:
      - ../:/workdir
    ports:
      - "3000:3000"
    stop_grace_period: 1s
    environment:
      CI_COMMIT_SHORT_SHA: main
    command: >
      sh -c "
      echo 'Starting Docusaurus server...' &&
      npm install &&
      npm run clear &&
      NODE_ENV=development npm run start -- --host 0.0.0.0
      "
