#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/docker.yml

stages:
  - test
  - publish

variables:
  SRSUE_VERSION: "23.11"
  SRSRAN_REPO_URL: https://github.com/srsran/srsRAN_4G.git
  SRSRAN_BRANCH: release_23_11

.docker-builder-srsue:
  extends: .docker-builder
  variables: &image_variables
    REGISTRY_URI: ${RETINA_REGISTRY_URI}
    NAME: srsue
    CONTEXT: retina/images/srsue
    VERSION: ${SRSUE_VERSION}_${RETINA_VERSION}
    BUILD_ARGS: REPO_URL=${SRSRAN_REPO_URL};REPO_BRANCH=${SRSRAN_BRANCH};RETINA_VERSION=${RETINA_VERSION};RETINA_REGISTRY_URI=${RETINA_REGISTRY_URI}

only-build:
  stage: test
  extends: .docker-builder-srsue
  rules:
    - if: $ON_MR
  variables:
    MODE: test

build-and-publish:
  stage: publish
  extends: .docker-builder-srsue
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  retry: 2
  variables:
    MODE: publish
    MULTI_ARCH_BUILD: "true"
  parallel:
    matrix:
      - PLATFORM: ["arm64", "amd64"]

publish manifest:
  stage: publish
  extends: .docker manifest
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    <<: *image_variables
  needs:
    - build-and-publish
