# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

include:
  - project: ocudu/ocudu
    file: .gitlab/ci-shared/workflow.yml
    ref: dev
  - project: ocudu/ocudu
    file: .gitlab/ci-shared/docker.yml
    ref: dev

variables:
  BUILDKIT_CLI_VERSION: "0.23.2"  # Override cached version from docker.yml

stages:
  - test
  - publish

.docker-builder-terraform:
  extends: .docker-builder
  variables:
    NAME: terraform
    CONTEXT: infrastructure/images/terraform
    REGISTRY_URI: ${GITLAB_REGISTRY_URI}
    VERSION: ${TERRAFORM_VERSION}
    BUILD_ARGS: TERRAFORM_VERSION=${TERRAFORM_VERSION}

only-build:
  stage: test
  extends: .docker-builder-terraform
  image: registry.gitlab.com/ocudu/ocudu/buildkit-cli:0.23.2
  rules:
    - if: $ON_MR
  variables:
    MODE: test

build-and-publish:
  stage: publish
  extends: .docker-builder-terraform
  image: registry.gitlab.com/ocudu/ocudu/buildkit-cli:0.23.2
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  retry: 2
  variables:
    MODE: publish
