# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

spec:
  inputs:
    ocudu_path:
      type: string
      default: ocudu/ocudu
      description: "OCUDU repository path."
    ocudu_ref:
      type: string
      default: dev
      description: "OCUDU reference branch or tag."
---
include:
  - project: $[[ inputs.ocudu_path ]]
    ref: $[[ inputs.ocudu_ref ]]
    file: .gitlab/ci-shared/docker.yml

stages:
  - test
  - publish

.docker-builder-android:
  extends: .docker-builder
  variables: &image_variables
    REGISTRY_URI: ${RETINA_REGISTRY_URI}
    NAME: android
    CONTEXT: retina/images/android
    VERSION: ${RETINA_VERSION}
    BUILD_ARGS: RETINA_VERSION=${RETINA_VERSION};RETINA_REGISTRY_URI=${RETINA_REGISTRY_URI}

only-build:
  stage: test
  extends: .docker-builder-android
  rules:
    - if: $ON_MR
  variables:
    MODE: test

build-and-publish:
  stage: publish
  extends: .docker-builder-android
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    MODE: publish
    MULTI_ARCH_BUILD: "true"
  parallel:
    matrix:
      - PLATFORM: ["arm64", "amd64"]

publish manifest:
  stage: publish
  extends: .docker manifest
  rules:
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_MR
      when: manual
      allow_failure: true
  variables:
    <<: *image_variables
  needs:
    - build-and-publish
