# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

# This script needs multiple environment variables to be set before running it.
# You can call the `generate_env.py` script to generate the environment variables.
# ```bash
# cd retina/_scripts
# python3 generate_env.py --ocudu-path ~/develop/ocudu
# ```

# Available profiles:
# - builders: Build gnb binary and amari-zmq driver
# - zmq_amariue_mme: Amarisoft UE + 2 OCUDU gNB + 1 OCUDU CU + 2 OCUDU DUs + Amarisoft 5GC
# - zmq_amariue_open5gs: Amarisoft UE + 2 OCUDU gNB + 1 OCUDU CU + 2 OCUDU DUs + Open5gs
# - zmq_srsue: srsUE + OCUDU gNB + Open5gs + Flexric
# - zmq_ntn: Amarisoft UE + 2 OCUDU gNB + 1 OCUDU CU + 2 OCUDU DUs + Open5gs + NTN Channel Emulator

services:
  ocudu-builder:
    container_name: ocudu-builder
    profiles:
      - all
      - builders
    image: ${BUILDER_IMAGE}
    volumes:
      - ${OCUDU_PATH}:/builds/ocudu/ocudu
    environment:
      CLICOLOR_FORCE: 1
    network_mode: "none"
    user: "${UID}:${GID}"
    command:
      [
        "builder.sh",
        "-b",
        "build_retina",
        "-c",
        "gcc",
        "-DBUILD_TESTING=False",
        "-DCMAKE_BUILD_TYPE=RelWithDebInfo",
        "-DASSERT_LEVEL=PARANOID",
        "-DMARCH=x86-64-v3",
        "-DLINKER=lld",
        "/builds/ocudu/ocudu",
      ]

  amari-zmq-builder:
    container_name: amari-zmq-builder
    profiles:
      - all
      - builders
    image: ${BUILDER_IMAGE}
    volumes:
      - ${OCUDU_PATH}:/builds/ocudu/ocudu
      - ${AMARISOFT_PATH}:/builds/amarisoftue
    environment:
      CLICOLOR_FORCE: 1
    network_mode: "none"
    user: "${UID}:${GID}"
    command:
      [
        "builder.sh",
        "-b",
        "build_trx_retina",
        "-x",
        "ccache_trx_retina",
        "-c",
        "gcc",
        "-m",
        "trx_ocudu_test",
        "-DBUILD_TESTING=False",
        "-DENABLE_EXPORT=True",
        "-DENABLE_UHD=False",
        "-DENABLE_ZEROMQ=True",
        "-DENABLE_TRX_DRIVER=True",
        "-DMARCH=x86-64-v3",
        "-DTRX_DRIVER_DIR=/builds/amarisoftue/trx_uhd-linux-${AMARISOFT_VERSION}",
        "/builds/ocudu/ocudu",
      ]

  launcher:
    container_name: launcher
    profiles:
      - all
      - zmq_amariue_mme
      - zmq_amariue_open5gs
      - zmq_srsue
      - zmq_ntn
      - launcher
    image: ${RETINA_REGISTRY_URI}/launcher:${RETINA_VERSION}
    build:
      context: ../
      dockerfile: launcher/Dockerfile
      network: host # dl.k8s.io sometimes can't be resolved in build network
      args: &variables
        RETINA_REGISTRY_URI: ${RETINA_REGISTRY_URI}
        RETINA_VERSION: ${RETINA_VERSION}
        AGENT_OS_VERSION: ${AGENT_OS_VERSION}
        AMARISOFT_VERSION: ${AMARISOFT_VERSION}
        BUILDER_IMAGE: ${BUILDER_IMAGE}
        OPEN5GS_VERSION: v${OPEN5GS_VERSION}
        FLEXRIC_VERSION: ${FLEXRIC_VERSION}
        NTN_CHANNEL_EMULATOR_VERSION: ${NTN_CHANNEL_EMULATOR_VERSION}
    environment:
      LOGNAME: $USER
      FORCE_COLOR: 1
      HOME: /home/$USER
    volumes:
      - ~/.kube:/home/$USER/.kube
      - ../..:/workdir
      # Following lines overwrite the retina code inside the container with your current code
      - ../protocol/src/retina/protocol:/usr/local/lib/python3.12/site-packages/retina/protocol
      - ../client/src/retina/client:/usr/local/lib/python3.12/site-packages/retina/client
      - ../orchestrator/src/retina/orchestrator:/usr/local/lib/python3.12/site-packages/retina/orchestrator
      - ../viavi/src/retina/viavi:/usr/local/lib/python3.12/site-packages/retina/viavi
      - ../launcher/src/retina/launcher:/usr/local/lib/python3.12/site-packages/retina/launcher
    working_dir: /workdir/e2e
    networks:
      retina:
        ipv4_address: 172.20.0.100
    user: "${UID}:${GID}"
    entrypoint: ["sh", "-c", "trap 'exit 0' SIGTERM; tail -f /dev/null & wait"]

  agent-image: &agent-image
    profiles:
      - all
      - zmq_amariue_mme
      - zmq_amariue_open5gs
      - zmq_srsue
      - zmq_ntn
    image: ${RETINA_REGISTRY_URI}/agent:${AGENT_OS_VERSION}
    build:
      context: ../
      dockerfile: agent/Dockerfile
      args:
        <<: *variables
    network_mode: "none"
    entrypoint: ["true"]

  wheelhouse:
    <<: *agent-image
    image: ${RETINA_REGISTRY_URI}/wheelhouse:${RETINA_VERSION}
    build:
      context: ../
      dockerfile: agent/Dockerfile.wheelhouse
      args:
        <<: *variables
    network_mode: "none"
    entrypoint: ["true"]

  amarisoft-ue:
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    container_name: amarisoft-ue
    profiles:
      - all
      - zmq_amariue_mme
      - zmq_amariue_open5gs
      - zmq_ntn
    image: ${RETINA_REGISTRY_URI}/amarisoftue:${AMARISOFT_VERSION}_${RETINA_VERSION}
    build:
      context: ../images/amarisoftue
      additional_contexts:
        agent: "service:agent-image"
        wheelhouse: "service:wheelhouse"
      args:
        <<: *variables
    environment:
      RETINA_IP: &amariue_ip 172.20.0.10
      RETINA_PORTS: 50064 50065 50066 50067 50068 50069 50070 50071 50072 50073 50074 50075 50076 50077 50078 50079 50080 50081 50082 50083 50084 50085 50086 50087 50088 50089 50090 50091 50092 50093 50094 50095 50096 50097 50098 50099 50100 50101 50102 50103 50104 50105 50106 50107 50108 50109 50110 50111 50112 50113 50114 50115 50116 50117 50118 50119 50120 50121 50122 50123 50124 50125 50126 50127
      RETINA_SECRETS: ${AMARISOFT_LICENSE_IP} ${AMARISOFT_UE_LICENSE_TAG}
    configs:
      - source: amari_ue_license.yml
        target: /etc/retina/resources/amarisoft_ue_license.yml
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - CAP_SYS_PTRACE
    sysctls:
      - net.ipv6.conf.default.disable_ipv6=0
    volumes: &agent_volumes
      - ${OCUDU_PATH}:/builds/ocudu/ocudu
      - ${OCUDU_PATH}/build_trx_retina/utils/trx_ocudu/libtrx_ocudu.so:/opt/lteue/trx_ocudu.so
      # Following lines overwrite the retina code inside the container with your current code
      - ../protocol/src/retina/protocol:/usr/local/lib/python3.12/dist-packages/retina/protocol
      - ../agent/src/retina/agent:/usr/local/lib/python3.12/dist-packages/retina/agent
    tmpfs: &agent_tmpfs
      - /var/log/retina
    networks:
      retina:
        ipv4_address: *amariue_ip
    devices:
      - /dev/net/tun:/dev/net/tun
    x-testbed:
      type: ue

  srs-ue:
    restart: unless-stopped
    container_name: srs-ue
    profiles:
      - all
      - zmq_srsue
    image: ${RETINA_REGISTRY_URI}/srsue:${SRSUE_VERSION}_${RETINA_VERSION}
    build:
      context: ../images/srsue
      args:
        <<: *variables
      additional_contexts:
        agent: "service:agent-image"
        wheelhouse: "service:wheelhouse"
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - CAP_SYS_PTRACE
    sysctls:
      - net.ipv6.conf.default.disable_ipv6=0
    environment:
      RETINA_IP: &srsue_ip 172.20.0.11
    networks:
      retina:
        ipv4_address: *srsue_ip
    volumes: *agent_volumes
    tmpfs: *agent_tmpfs
    devices:
      - /dev/net/tun:/dev/net/tun
    x-testbed:
      type: ue

  ocudu-gnb-1: &gnb_service
    restart: unless-stopped
    container_name: ocudu-gnb-1
    profiles:
      - all
      - zmq_amariue_mme
      - zmq_amariue_open5gs
      - zmq_srsue
      - zmq_ntn
    image: ${RETINA_REGISTRY_URI}/ocudu:${RETINA_VERSION}
    build:
      context: ../images/ocudu
      args:
        <<: *variables
      additional_contexts:
        agent: "service:agent-image"
        wheelhouse: "service:wheelhouse"
    cap_add:
      - SYS_NICE
      - CAP_SYS_PTRACE
    volumes: *agent_volumes
    tmpfs: *agent_tmpfs
    environment: &ocudu_env
      RETINA_AGENT: ocudu-gnb
      RETINA_IP: &gnb0_ip 172.20.0.20
      PATH: ${CONTAINER_PATH}:/builds/ocudu/ocudu/build_retina/apps/gnb:/builds/ocudu/ocudu/build_retina/apps/cu:/builds/ocudu/ocudu/build_retina/apps/cu_cp:/builds/ocudu/ocudu/build_retina/apps/cu_up:/builds/ocudu/ocudu/build_retina/apps/du
    networks:
      retina:
        ipv4_address: *gnb0_ip
    x-testbed:
      type: gnb

  ocudu-gnb-2:
    <<: *gnb_service
    container_name: ocudu-gnb-2
    environment:
      <<: *ocudu_env
      RETINA_IP: &gnb1_ip 172.20.0.21
    networks:
      retina:
        ipv4_address: *gnb1_ip
    x-testbed:
      type: gnb

  ocudu-cu:
    <<: *gnb_service
    container_name: ocudu-cu
    environment:
      <<: *ocudu_env
      RETINA_AGENT: ocudu-cu
      RETINA_IP: &cu_ip 172.20.0.30
    networks:
      retina:
        ipv4_address: *cu_ip
    x-testbed:
      type: cu

  ocudu-cu-cp:
    <<: *gnb_service
    container_name: ocudu-cu-cp
    environment:
      <<: *ocudu_env
      RETINA_AGENT: ocudu-cu-cp
      RETINA_IP: &cu_cp_ip 172.20.0.40
    networks:
      retina:
        ipv4_address: *cu_cp_ip
    x-testbed:
      type: cu_cp

  ocudu-cu-up:
    <<: *gnb_service
    container_name: ocudu-cu-up
    environment:
      <<: *ocudu_env
      RETINA_AGENT: ocudu-cu-up
      RETINA_IP: &cu_up_ip 172.20.0.50
    networks:
      retina:
        ipv4_address: *cu_up_ip
    x-testbed:
      type: cu_up

  ocudu-du-1:
    <<: *gnb_service
    container_name: ocudu-du-1
    environment:
      <<: *ocudu_env
      RETINA_AGENT: ocudu-du
      RETINA_IP: &du0_ip 172.20.0.60
    networks:
      retina:
        ipv4_address: *du0_ip
    x-testbed:
      type: du

  ocudu-du-2:
    <<: *gnb_service
    container_name: ocudu-du-2
    environment:
      <<: *ocudu_env
      RETINA_AGENT: ocudu-du
      RETINA_IP: &du1_ip 172.20.0.61
    networks:
      retina:
        ipv4_address: *du1_ip
    x-testbed:
      type: du

  open5gs:
    restart: unless-stopped
    container_name: open5gs
    profiles:
      - all
      - zmq_amariue_open5gs
      - zmq_srsue
      - zmq_ntn
    image: ${RETINA_REGISTRY_URI}/open5gs:${OPEN5GS_VERSION}_${RETINA_VERSION}
    build:
      context: ../images/open5gs
      args:
        <<: *variables
      additional_contexts:
        agent: "service:agent-image"
        wheelhouse: "service:wheelhouse"
    cap_add:
      - NET_ADMIN
      - CAP_SYS_PTRACE
    sysctls:
      - net.ipv6.conf.default.disable_ipv6=0
    environment:
      RETINA_IP: &open5gs_ip 172.20.0.70
    networks:
      retina:
        ipv4_address: *open5gs_ip
    volumes: *agent_volumes
    tmpfs: *agent_tmpfs
    devices:
      - /dev/net/tun:/dev/net/tun
    x-testbed:
      type: 5gc

  amarisoft-5gc-1: &mme
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    container_name: amarisoft-5gc-1
    profiles:
      - all
      - zmq_amariue_mme
    image: ${RETINA_REGISTRY_URI}/amarisoft5gc:${AMARISOFT_VERSION}_${RETINA_VERSION}
    build:
      context: ../images/amarisoft5gc
      args:
        <<: *variables
      additional_contexts:
        agent: "service:agent-image"
        wheelhouse: "service:wheelhouse"
    environment:
      RETINA_IP: &amari5gc1_ip 172.20.0.71
      RETINA_SECRETS: ${AMARISOFT_LICENSE_IP} ${AMARISOFT_MME_LICENSE_TAG}
    cap_add:
      - NET_ADMIN # Required for TUN interface creation and iptables
    configs:
      - source: amari_mme_license.yml
        target: /etc/retina/resources/amarisoft_mme_license.yml
    sysctls:
      - net.ipv6.conf.default.disable_ipv6=1 # Prevent IPv6 issues
      - net.ipv4.ip_forward=1 # Required for packet forwarding between UEs and network
    networks:
      retina:
        ipv4_address: *amari5gc1_ip
    volumes: *agent_volumes
    tmpfs: *agent_tmpfs
    devices:
      - /dev/net/tun:/dev/net/tun
    x-testbed:
      type: 5gc

  amarisoft-5gc-2:
    <<: *mme
    container_name: amarisoft-5gc-2
    environment:
      RETINA_IP: &amari5gc2_ip 172.20.0.72
      RETINA_SECRETS: ${AMARISOFT_LICENSE_IP} ${AMARISOFT_MME_LICENSE_TAG}
    networks:
      retina:
        ipv4_address: *amari5gc2_ip

  ntn-channel-emulator:
    restart: unless-stopped
    container_name: ntn-channel-emulator
    profiles:
      - all
      - zmq_ntn
    image: ${RETINA_REGISTRY_URI}/ntn-channel-emulator:${NTN_CHANNEL_EMULATOR_VERSION}_${RETINA_VERSION}
    build:
      context: ../images/ntn-channel-emulator
      args:
        <<: *variables
      additional_contexts:
        agent: "service:agent-image"
        wheelhouse: "service:wheelhouse"
    environment:
      RETINA_IP: &emulator_ip 172.20.0.80
    networks:
      retina:
        ipv4_address: *emulator_ip
    tmpfs: *agent_tmpfs
    x-testbed:
      type: channel-emulator

  flexric:
    restart: unless-stopped
    container_name: flexric
    profiles:
      - all
      - zmq_srsue
    image: ${RETINA_REGISTRY_URI}/flexric:${FLEXRIC_VERSION}_${RETINA_VERSION}
    build:
      context: ../images/flexric
      args:
        <<: *variables
      additional_contexts:
        agent: "service:agent-image"
        wheelhouse: "service:wheelhouse"
    environment:
      RETINA_IP: &flexric_ip 172.20.0.90
    networks:
      retina:
        ipv4_address: *flexric_ip
    tmpfs: *agent_tmpfs
    x-testbed:
      type: ric

configs:
  amari_ue_license.yml:
    content: |
      - type: License
        address: ${AMARISOFT_LICENSE_IP}
        args: ${AMARISOFT_UE_LICENSE_TAG}
  amari_mme_license.yml:
    content: |
      - type: License
        address: ${AMARISOFT_LICENSE_IP}
        args: ${AMARISOFT_MME_LICENSE_TAG}
  amari_remote_ue.yml:
    content: |
      - type: Remote
        address: ${AMARISOFT_REMOTE_UE_IP:-}
        user: unknown
        password: unknown
        path: "/opt/lteue"
      - type: API
        address: ${AMARISOFT_REMOTE_UE_IP:-}
        port: 9002
  gnb_remote.yml:
    content: |
      - type: Remote
        address: ${GNB_REMOTE_IP:-}
        user: unknown
        password: unknown
        path: ""

networks:
  retina:
    name: retina_local_network
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
        - subnet: fd00:0:0:1::/64
          gateway: fd00:0:0:1::1
